-- Missions / Quests / Campaigns / Coalitions
return {
	sandoria = {
		[0] = "A Sentry's Peril",
		[1] = "Waters of the Cheval",
		[2] = "Rosel the Armorer",
		[3] = "The Pickpocket",
		[4] = "Father and Son",
		[5] = "The Seamstress",
		[6] = "The Dismayed Customer",
		[7] = "The Trader in the Forest",
		[8] = "The Sweetest Things",
		[9] = "The Vicasque's Sermon",
		[10] = "A Squire's Test",
		[11] = "Grave Concerns",
		[12] = "The Brugaire Consortium",
		[15] = "Lizard Skins",
		[16] = "Flyers for Regine",
		[18] = "Gates to Paradise",
		[19] = "A Squire's Test II",
		[20] = "To Cure a Cough",
		[23] = "Tiger's Teeth",
		[26] = "Undying Flames",
		[27] = "A Purchase of Arms",
		[29] = "A Knight's Test",
		[30] = "The Medicine Woman",
		[31] = "Black Tiger Skins",
		--[32] = "SDクエスト32",
		--[33] = "SDクエスト33",
		--[34] = "SDクエスト34",
		--[35] = "SDクエスト35",
		--[36] = "SDクエスト36",
		--[37] = "SDクエスト37",
		--[38] = "SDクエスト38",
		--[39] = "SDクエスト39",
		--[40] = "SDクエスト40",
		--[41] = "SDクエスト41",
		--[42] = "SDクエスト42",
		--[43] = "SDクエスト43",
		--[44] = "SDクエスト44",
		--[45] = "SDクエスト45",
		--[46] = "SDクエスト46",
		--[47] = "SDクエスト47",
		--[48] = "SDクエスト48",
		--[49] = "SDクエスト49",
		--[50] = "SDクエスト50",
		--[51] = "SDクエスト51",
		--[52] = "SDクエスト52",
		--[53] = "SDクエスト53",
		--[54] = "SDクエスト54",
		--[55] = "SDクエスト55",
		--[56] = "SDクエスト56",
		--[57] = "SDクエスト57",
		[58] = "Growing Flowers",
		[59] = "+Trial by Ice",
		[60] = "The General's Secret",
		[61] = "The Rumor",
		[62] = "Her Majesty's Garden",
		[63] = "Introduction to Teamwork",
		[64] = "Intermediate Teamwork",
		[65] = "Advanced Teamwork",
		[66] = "Grimy Signposts",
		[67] = "A Job for the Consortium",
		[68] = "Trouble at the Sluice",
		[69] = "The Merchant's Bidding",
		[70] = "Unexpected Treasure",
		[71] = "Blackmail",
		[72] = "The Setting Sun",
		[74] = "Distant Loyalties",
		[75] = "The Rivalry",
		[76] = "The Competition",
		[77] = "Starting a Flame",
		[78] = "Fear of the Dark",
		[79] = "Warding Vampires",
		[80] = "Sleepless Nights",
		[81] = "Lufet's Lake Salt",
		[82] = "Healing the Land",
		[83] = "Sorcery of the North",
		[84] = "The Crimson Trial",
		[85] = "Enveloped in Darkness",
		[86] = "Peace for the Spirit",
		[87] = "Messenger from Beyond",
		[88] = "Prelude of Black and White",
		[89] = "Pieuje's Decision",
		[90] = "Sharpening the Sword",
		[91] = "A Boy's Dream",
		[92] = "Under Oath",
		[93] = "The Holy Crest",
		[94] = "A Craftsman's Work",
		[95] = "Chasing Quotas",
		[96] = "Knight Stalker",
		[97] = "+Eco-Warrior",
		[98] = "Methods Create Madness",
		[99] = "Souls in Shadow",
		[100] = "A Taste for Meat",
		[101] = "Exit the Gambler",
		[102] = "Old Wounds",
		[103] = "+Escort for Hire (San d'Oria)",
		[104] = "+A Discerning Eye (San d'Oria)",
		[105] = "A Timely Visit",
		[106] = "Fit for a Prince",
		[107] = "Trial-Size Trial by Ice",
		[108] = "Signed in Blood",
		[109] = "Tea with a Tonberry?",
		[110] = "+Spice Gals",
		--[111] = "SDクエスト111",
		[112] = "Over the Hills and Far Away",
		[113] = "Lure of the Wildcat (San d'Oria)",
		[114] = "Atelloune's Lament",
		--[115] = "SDクエスト115",
		--[116] = "SDクエスト116",
		[117] = "Thick Shells",
		[118] = "Forest for the Trees",
		[119] = "Trust: San d'Oria",
		--[120] = "SDクエスト120",
	},
	bastok = {
		[0] = "The Siren's Tear",
		[1] = "Beauty and the Galka",
		[2] = "Welcome to Bastok",
		[3] = "Guest of Hauteur",
		[4] = "The Quadav's Curse",
		[5] = "Out of One's Shell",
		[6] = "Hearts of Mythril",
		[7] = "The Eleventh's Hour",
		[8] = "Shady Business",
		[9] = "A Foreman's Best Friend",
		[10] = "Breaking Stones",
		[11] = "The Cold Light of Day",
		[12] = "Gourmet",
		[13] = "+The Elvaan Goldsmith",
		[14] = "A Flash in the Pan",
		[15] = "Smoke on the Mountain",
		[16] = "Stamp Hunt",
		[17] = "Forever to Hold",
		[18] = "Till Death Do Us Part",
		[19] = "Fallen Comrades",
		[20] = "Rivals",
		[21] = "Mom, the Adventurer?",
		[22] = "The Signpost Marks the Spot",
		[23] = "Past Perfect",
		[24] = "Stardust",
		[25] = "Mean Machine",
		[26] = "Cid's Secret",
		[27] = "The Usual",
		[28] = "Blade of Darkness",
		[29] = "Father Figure",
		[30] = "The Return of the Adventurer",
		[31] = "Drachenfall",
		[32] = "Vengeful Wrath",
		[33] = "Beadeaux Smog",
		[34] = "The Curse Collector",
		[35] = "Fear of Flying",
		[36] = "The Wisdom of Elders",
		[37] = "Groceries",
		[38] = "The Bare Bones",
		[39] = "Minesweeper",
		[40] = "The Darksmith",
		[41] = "Buckets of Gold",
		[42] = "The Stars of Ifrit",
		[43] = "Love and Ice",
		[44] = "Brygid the Stylist",
		[45] = "The Gustaberg Tour",
		[46] = "Bite the Dust",
		[47] = "Blade of Death",
		[48] = "Silence of the Rams",
		[49] = "Altana's Sorrow",
		[50] = "A Lady's Heart",
		[51] = "Ghosts of the Past",
		[52] = "The First Meeting",
		[53] = "True Strength",
		[54] = "The Doorman",
		[55] = "The Talekeeper's Truth",
		[56] = "The Talekeeper's Gift",
		[57] = "Dark Legacy",
		[58] = "Dark Puppet",
		[59] = "Blade of Evil",
		[60] = "Ayame and Kaede",
		[61] = "+Trial by Earth",
		[62] = "A Test of True Love",
		[63] = "Lovers in the Dusk",
		[64] = "Wish Upon a Star",
		[65] = "+Eco-Warrior",
		[66] = "The Weight of Your Limits",
		[67] = "Shoot First, Ask Questions Later",
		[68] = "Inheritance",
		[69] = "The Walls of Your Mind",
		[70] = "+Escort for Hire (Bastok)",
		[71] = "+A Discerning Eye (Bastok)",
		[72] = "Trial-Size Trial by Earth",
		[73] = "Faded Promises",
		[74] = "+Brygid the Stylist Returns",
		[75] = "Out of the Depths",
		[76] = "+All by Myself",
		[77] = "A Question of Faith",
		[78] = "Return to the Depths",
		[79] = "Teak Me to the Stars",
		[80] = "Hyper Active",
		[81] = "The Naming Game",
		[82] = "Chips",
		[83] = "Bait and Switch",
		[84] = "Lure of the Wildcat (Bastok)",
		[85] = "Achieving True Power",
		[86] = "Too Many Chefs",
		[87] = "A Proper Burial",
		[88] = "Fully Mental Alchemist",
		[89] = "Synergistic Pursuits",
		[90] = "The Wondrous Whatchamacallit",
		[91] = "Synergistic Support",
		[92] = "Trust: Bastok",
		--[93] = "BSクエスト93",
		--[94] = "BSクエスト94",
		--[95] = "BSクエスト95",
		--[96] = "BSクエスト96",
		--[97] = "BSクエスト97",
		--[99] = "BSクエスト99",
	},
	windurst = {
		[0] = "Hat in Hand",
		[1] = "A Feather in One's Cap",
		[2] = "A Crisis in the Making",
		[3] = "Making Amends",
		[4] = "Making the Grade",
		[5] = "In a Pickle",
		[6] = "Wondering Minstrel",
		[7] = "A Pose by Any Other Name",
		[8] = "Making Amens!",
		[9] = "+The Moonlit Path",
		[10] = "Star Struck",
		[11] = "Blast from the Past",
		[12] = "A Smudge on One's Record",
		[13] = "Chasing Tales",
		[14] = "Food for Thought",
		[15] = "Overnight Delivery",
		[16] = "Water Way to Go!",
		[17] = "Blue Ribbon Blues",
		[18] = "The All-New C-3000",
		[19] = "The Postman Always K.O.'s Twice",
		[20] = "Early Bird Catches the Bookworm",
		[21] = "Catch It If You Can!",
		--[22] = "Windurst Quest #22",
		[23] = "All at Sea",
		[24] = "The All-New C-2000",
		[25] = "Mihgo's Amigo",
		[26] = "Rock Racketeer",
		[27] = "Chocobilious",
		[28] = "Teacher's Pet",
		[29] = "Reap What You Sow",
		[30] = "Glyph Hanger",
		[31] = "The Fanged One",
		[32] = "Curses, Foiled Again!",
		[33] = "Curses, Foiled...Again!?",
		[34] = "Mandragora-Mad",
		[35] = "To Bee or Not to Bee?",
		[36] = "Truth, Justice, and the Onion Way!",
		[37] = "Making Headlines",
		[38] = "Scooped!",
		[39] = "Creepy Crawlies",
		[40] = "Know One's Onions",
		[41] = "Inspector's Gadget!",
		[42] = "Onion Rings",
		[43] = "A Greeting Cardian",
		[44] = "Legendary Plan B",
		[45] = "In a Stew",
		[46] = "Let Sleeping Dogs Lie",
		[47] = "Can Cardians Cry?",
		[48] = "Wonder Wands",
		[49] = "Heaven Cent",
		[50] = "Say It with Flowers",
		[51] = "Hoist the Jelly, Roger",
		[52] = "Something Fishy",
		[53] = "To Catch a Falling Star",
		--[54] = "Windurst Quest #54",
		--[55] = "Windurst Quest #55",
		--[56] = "Windurst Quest #56",
		--[57] = "Windurst Quest #57",
		--[58] = "Windurst Quest #58",
		--[59] = "Windurst Quest #59",
		[60] = "Paying Lip Service",
		[61] = "The Amazin' Scorpio",
		[62] = "Twinstone Bonding",
		[63] = "Curses, Foiled A-Golem!?",
		[64] = "Acting in Good Faith",
		[65] = "Flower Child",
		[66] = "The Three Magi",
		[67] = "Recollections",
		[68] = "The Root of the Problem",
		[69] = "The Tenshodo Showdown",
		[70] = "As Thick as Thieves",
		[71] = "Hitting the Marquisate",
		[72] = "Sin Hunting",
		[73] = "Fire and Brimstone",
		[74] = "Unbridled Passion",
		[75] = "I Can Hear a Rainbow",
		[76] = "Crying Over Onions",
		[77] = "Wild Card",
		[78] = "The Promise",
		[79] = "Nothing Matters",
		[80] = "Toraimarai Turmoil",
		[81] = "The Puppet Master",
		[82] = "Class Reunion",
		[83] = "Carbuncle Debacle",
		[84] = "+Eco-Warrior",
		[85] = "From Saplings Grow",
		[86] = "Orastery Woes",
		[87] = "Blood and Glory",
		[88] = "+Escort for Hire (Windurst)",
		[89] = "+A Discerning Eye (Windurst)",
		[90] = "Tuning In",
		[91] = "Tuning Out",
		[92] = "One Good Deed?",
		[93] = "+Waking Dreams",
		[94] = "Lure of the Wildcat (Windurst)",
		[95] = "Babban Ny Mheillea",
		[96] = "Trust: Windurst",
		--[99] = "Windurst Quest #99",
	},
	jeuno = {
		[0] = "Crest of Davoi",
		[1] = "Save My Sister",
		[2] = "A Clock Most Delicate",
		[3] = "Save the Clock Tower",
		[4] = "Chocobo's Wounds",
		[5] = "Save My Son",
		[6] = "A Candlelight Vigil",
		[7] = "The Wonder Magic Set",
		[8] = "The Kind Cardian",
		[9] = "Your Crystal Ball",
		[10] = "Collect Tarut Cards",
		[11] = "The Old Monument",
		[12] = "A Minstrel in Despair",
		[13] = "Rubbish Day",
		[14] = "Never to Return",
		[15] = "Community Service",
		[16] = "Cook's Pride",
		[17] = "Tenshodo Membership",
		[18] = "The Lost Cardian",
		[19] = "Path of the Beastmaster",
		[20] = "Path of the Bard",
		[21] = "The Clockmaster",
		[22] = "Candle-making",
		[23] = "Child's Play",
		[24] = "Northward",
		[25] = "The Antique Collector",
		[26] = "Deal with Tenshodo",
		[27] = "The Gobbiebag Part I",
		[28] = "The Gobbiebag Part II",
		[29] = "The Gobbiebag Part III",
		[30] = "The Gobbiebag Part IV",
		[31] = "Mysteries of Beadeaux I",
		[32] = "Mysteries of Beadeaux II",
		--[33] = "Mystery of Fire",
		--[34] = "Mystery of Water",
		--[35] = "Mystery of Earth",
		--[36] = "Mystery of Wind",
		--[37] = "Mystery of Ice",
		--[38] = "Mystery of Lightning",
		--[39] = "Mystery of Light",
		--[40] = "Mystery of Darkness",
		[41] = "Fistful of Fury",
		[42] = "The Goblin Tailor",
		[43] = "Pretty Little Things",
		[44] = "Borghertz's Warring Hands",
		[45] = "Borghertz's Striking Hands",
		[46] = "Borghertz's Healing Hands",
		[47] = "Borghertz's Sorcerous Hands",
		[48] = "Borghertz's Vermillion Hands",
		[49] = "Borghertz's Sneaky Hands",
		[50] = "Borghertz's Stalwart Hands",
		[51] = "Borghertz's Shadowy Hands",
		[52] = "Borghertz's Wild Hands",
		[53] = "Borghertz's Harmonious Hands",
		[54] = "Borghertz's Chasing Hands",
		[55] = "Borghertz's Loyal Hands",
		[56] = "Borghertz's Lurking Hands",
		[57] = "Borghertz's Dragon Hands",
		[58] = "Borghertz's Calling Hands",
		[59] = "Axe the Competition",
		[60] = "Wings of Gold",
		[61] = "Scattered Into Shadow",
		[62] = "A New Dawn",
		[63] = "Painful Memory",
		[64] = "The Requiem",
		[65] = "The Circle of Time ",
		[66] = "Searching for the Right Words",
		[67] = "Beat Around the Bushin",
		[68] = "+Ducal Hospitality",
		[69] = "In the Mood for Love",
		[70] = "Empty Memories",
		[71] = "Hook, Line, and Sinker",
		[72] = "A Chocobo's Tale",
		[73] = "A Reputation in Ruins",
		[74] = "The Gobbiebag Part V",
		[75] = "The Gobbiebag Part VI",
		[76] = "Beyond the Sun",
		[77] = "Unlisted Qualities",
		[78] = "Girl in the Looking Glass",
		[79] = "Mirror, Mirror",
		[80] = "Past Reflections",
		[81] = "Blighted Gloom",
		[82] = "Blessed Radiance",
		[83] = "Mirror Images",
		[84] = "Chameleon Capers",
		[85] = "Regaining Trust",
		[86] = "Storms of Fate",
		[87] = "Mixed Signals",
		[88] = "Shadows of the Departed",
		[89] = "Apocalypse Nigh",
		[90] = "Lure of the Wildcat (Jeuno)",
		[91] = "The Road to Aht Urhgan",
		[92] = "Chocobo on the Loose!",
		[93] = "The Gobbiebag Part VII",
		[94] = "The Gobbiebag Part VIII",
		[95] = "Lakeside Minuet",
		[96] = "The Unfinished Waltz",
		[97] = "The Road to Divadom",
		[98] = "Comeback Queen",
		[99] = "A Furious Finale",
		[100] = "The Miraculous Dale",
		[101] = "Clash of the Comrades",
		[102] = "Unlocking a Myth (Warrior)",
		[103] = "Unlocking a Myth (Monk)",
		[104] = "Unlocking a Myth (White Mage)",
		[105] = "Unlocking a Myth (Black Mage)",
		[106] = "Unlocking a Myth (Red Mage)",
		[107] = "Unlocking a Myth (Thief)",
		[108] = "Unlocking a Myth (Paladin)",
		[109] = "Unlocking a Myth (Dark Knight)",
		[110] = "Unlocking a Myth (Beastmaster)",
		[111] = "Unlocking a Myth (Bard)",
		[112] = "Unlocking a Myth (Ranger)",
		[113] = "Unlocking a Myth (Samurai)",
		[114] = "Unlocking a Myth (Ninja)",
		[115] = "Unlocking a Myth (Dragoon)",
		[116] = "Unlocking a Myth (Summoner)",
		[117] = "Unlocking a Myth (Blue Mage)",
		[118] = "Unlocking a Myth (Corsair)",
		[119] = "Unlocking a Myth (Puppetmaster)",
		[120] = "Unlocking a Myth (Dancer)",
		[121] = "Unlocking a Myth (Scholar)",
		--[122] = "JNQuest",
		[123] = "The Gobbiebag Part IX",
		[124] = "The Gobbiebag Part X",
		--[125] = "JNQuest",
		--[126] = "JNQuest",
		--[127] = "JNQuest",
		[128] = "In Defiant Challenge",
		[129] = "Atop the Highest Mountains",
		[130] = "Whence Blows the Wind",
		[131] = "Riding on the Clouds",
		[132] = "Shattering Stars",
		[133] = "New Worlds Await",
		[134] = "Expanding Horizons",
		[135] = "Beyond the Stars",
		[136] = "Dormant Powers Dislodged",
		[137] = "Beyond Infinity",
		
		[160] = "A Trial in Tandem",
		[161] = "A Trial in Tandem, Redux",
		[162] = "Yet Another Trial in Tandem",
		[163] = "A Quaternary Trial in Tandem",
		[164] = "A Trial in Tandem Revisited",
		--[165] = "（仮）",
		[166] = "+All in the Cards",
		[167] = "Martial Mastery",
		[168] = "VW Op. #115: Valkurm Duster",
		[169] = "VW Op. #118: Buburimu Squall",
		[170] = "Prelude to Puissance",
		[171] = "Researchers from the West",
		[172] = "Middle Lands Investigation",
		[173] = "Further Founts",
		[174] = "+Beam Me Up...No, Not There!",
		[175] = "+Now Recording...",
		[176] = "Teleports by Twilight",
		[177] = "Shifty Shades of Prey",
		[178] = "To Kill Mocking Birds",
		[179] = "Full Speed Ahead!",
		
		[186] = "The Flying Machine of Eld",
	},
	other = {
		[0] = "Rycharde the Chef",
		[1] = "Way of the Cook",
		[2] = "Unending Chase",
		[3] = "His Name Is Valgeir",
		[4] = "Expertise",
		[5] = "The Clue",
		[6] = "The Basics",
		[7] = "Orlando's Antiques",
		[8] = "The Sand Charm",
		[9] = "A Potter's Preference",
		[10] = "The Old Lady",
		[11] = "Fisherman's Heart",
		--[12] = "OTクエスト12",
		--[13] = "OTクエスト13",
		--[14] = "OTクエスト14",
		--[15] = "OTクエスト15",
		[16] = "Donate to Recycling",
		[17] = "Under the Sea",
		[18] = "Only the Best",
		[19] = "An Explorer's Footsteps",
		[20] = "Cargo",
		[21] = "The Gift",
		[22] = "The Real Gift",
		[23] = "The Rescue",
		[24] = "Elder Memories",
		[25] = "+Test My Mettle",
		[26] = "Inside the Belly",
		[27] = "+Trial by Lightning",
		[28] = "Trial-Size Trial by Lightning",
		[29] = "It's Raining Mannequins",
		[30] = "Recycling Rods",
		[31] = "Picture Perfect",
		[32] = "+Waking the Beast",
		[33] = "Survival of the Wisest",
		[34] = "Monstrosity",
		[35] = "Kupofried's H2H Moogle Magic",
		[36] = "Kupofried's Dagger Moogle Magic",
		[37] = "Kupofried's Sword Moogle Magic",
		[38] = "Kupofried's Great Sword Moogle Magic",
		[39] = "Kupofried's Axe Moogle Magic",
		[40] = "Kupofried's Great Axe Moogle Magic",
		[41] = "Kupofried's Scythe Moogle Magic",
		[42] = "Kupofried's Polearm Moogle Magic",
		[43] = "Kupofried's Katana Moogle Magic",
		[44] = "Kupofried's Great Katana Moogle Magic",
		[45] = "Kupofried's Club Moogle Magic",
		[46] = "Kupofried's Staff Moogle Magic",
		[47] = "Kupofried's Archery Moogle Magic",
		[48] = "Kupofried's Marksmanship Moogle Magic",
		--[49] = "OTクエスト49",
		--[50] = "OTクエスト50",
		--[51] = "OTクエスト51",
		--[52] = "OTクエスト52",
		--[53] = "OTクエスト53",
		--[54] = "OTクエスト54",
		--[55] = "OTクエスト55",
		--[56] = "OTクエスト56",
		--[57] = "OTクエスト57",
		--[58] = "OTクエスト58",
		--[59] = "OTクエスト59",
		--[60] = "OTクエスト60",
		--[61] = "OTクエスト61",
		--[62] = "OTクエスト62",
		--[63] = "OTクエスト63",
		[64] = "A Hard Day's Knight",
		[65] = "X Marks the Spot",
		[66] = "A Bitter Past",
		[67] = "The Call of the Sea",
		[68] = "Paradise, Salvation, and Maps",
		[69] = "Go! Go! Gobmuffin!",
		[70] = "+The Big One",
		[71] = "Fly High",
		[72] = "Unforgiven",
		[73] = "+Secrets of Ovens Lost",
		[74] = "Petals for Parelbriaux",
		[75] = "Elderly Pursuits",
		[76] = "In the Name of Science",
		[77] = "Behind the Smile",
		[78] = "Knocking on Forbidden Doors",
		[79] = "Confessions of a Bellmaker",
		[80] = "In Search of the Truth",
		[81] = "+Uninvited Guests",
		[82] = "Tango with a Tracker",
		[83] = "Requiem of Sin",
		[84] = "VW Op. #026: Tavnazian Terrors",
		[85] = "VW Op. #004: Bibiki Bombardment",
		--[86] = "OTクエスト86",
		--[87] = "OTクエスト87",
		--[88] = "OTクエスト88",
		--[89] = "OTクエスト89",
		--[90] = "OTクエスト90",
		--[91] = "OTクエスト91",
		--[92] = "OTクエスト92",
		--[93] = "OTクエスト93",
		--[94] = "OTクエスト94",
		--[95] = "OTクエスト95",
		[96] = "Bombs Away!",
		[97] = "Mithran Delicacies",
		--[99] = "OTクエスト99",
		[100] = "Give a Moogle a Break",
		[101] = "The Moogle's Picnic!",
		[102] = "Moogles in the Wild",
		[103] = "Missionary Moblin",
		[104] = "For the Birds",
		[105] = "Better the Demon You Know",
		[106] = "+An Understanding Overlord?",
		[107] = "+An Affable Adamantking?",
		[108] = "+A Moral Manifest?",
		[109] = "+A Generous General?",
		[110] = "Records of Eminence",
		[111] = "Unity Concord",
		[200] = "Titillating Tomes",
		[201] = "Release the Fleece",
		[202] = "Feeding Frenzy",
		[203] = "Cry Not, Caretaker",
		[204] = "Chacharoon's Cheer",
		[205] = "Trial of the Chacharoon",
		[206] = "Doctor Chacharoon",
		[207] = "Rowing Together",
		[208] = "Glittering Gals",
		[209] = "Sally Forth!",
		-- these are from 'Other' DAT File but should be represented in adoulin packet (id minus 1000)
		--[1039] = "Full Fields",
		--[1040] = "Green Groves",
		--[1041] = "Mining Missive",
		--[1042] = "Pond Probing",
		--[1043] = "Coastal Chaos",
		--[1044] = "Seed Sowing",
		--[1045] = "Flotsam Finding",
		--[1047] = "Courtesy Crustacean",
		--[1048] = "Trinket for the Tyrant",
		--[1049] = "Hypnotic Hospitality",
	},
	outlands = {
		--[0] = "FR Quest 0",
		[1] = "+The Firebloom Tree",
		[2] = "+Greetings to the Guardian",
		[3] = "+A Question of Taste",
		[4] = "Everyone's Grudging",
		--[5] = "FR Quest 5",
		[6] = "You Call That a Knife?",
		[7] = "Missionary Man",
		[8] = "Gullible's Travels",
		[9] = "Even More Gullible's Travels",
		[10] = "Personal Hygiene",
		[11] = "The Opo-opo and I",
		[12] = "+Trial by Fire",
		[13] = "Cloak and Dagger",
		[14] = "+A Discerning Eye (Kazham)",
		[15] = "Trial-Size Trial by Fire",
		--[16] = "FRクエスト16",
		--[17] = "FRクエスト17",
		--[18] = "FRクエスト18",
		--[19] = "FRクエスト19",
		--[20] = "FRクエスト20",
		--[21] = "FRクエスト21",
		--[22] = "FRクエスト22",
		--[23] = "FRクエスト23",
		--[24] = "FRクエスト24",
		--[25] = "FRクエスト25",
		--[26] = "FRクエスト26",
		--[27] = "FRクエスト27",
		--[28] = "FRクエスト28",
		--[29] = "FRクエスト29",
		--[30] = "FRクエスト30",
		--[31] = "FRクエスト31",
		--[32] = "FRクエスト32",
		--[33] = "FRクエスト33",
		--[34] = "FRクエスト34",
		--[35] = "FRクエスト35",
		--[36] = "FRクエスト36",
		--[37] = "FRクエスト37",
		--[38] = "FRクエスト38",
		--[39] = "FRクエスト39",
		--[40] = "FRクエスト40",
		--[41] = "FRクエスト41",
		--[42] = "FRクエスト42",
		--[43] = "FRクエスト43",
		--[44] = "FRクエスト44",
		--[45] = "FRクエスト45",
		--[46] = "FRクエスト46",
		--[47] = "FRクエスト47",
		--[48] = "FRクエスト48",
		--[49] = "FRクエスト49",
		--[50] = "FRクエスト50",
		--[51] = "FRクエスト51",
		--[52] = "FRクエスト52",
		--[53] = "FRクエスト53",
		--[54] = "FRクエスト54",
		--[55] = "FRクエスト55",
		--[56] = "FRクエスト56",
		--[57] = "FRクエスト57",
		--[58] = "FRクエスト58",
		--[59] = "FRクエスト59",
		--[60] = "FRクエスト60",
		--[61] = "FRクエスト61",
		--[62] = "FRクエスト62",
		--[63] = "FRクエスト63",
		--[64] = "FRクエスト64",
		--[65] = "FRクエスト65",
		--[66] = "FRクエスト66",
		--[67] = "FRクエスト67",
		--[68] = "FRクエスト68",
		--[69] = "FRクエスト69",
		--[70] = "FRクエスト70",
		--[71] = "FRクエスト71",
		--[72] = "FRクエスト72",
		--[73] = "FRクエスト73",
		--[74] = "FRクエスト74",
		--[75] = "FRクエスト75",
		--[76] = "FRクエスト76",
		--[77] = "FRクエスト77",
		--[78] = "FRクエスト78",
		--[79] = "FRクエスト79",
		--[80] = "FRクエスト80",
		--[81] = "FRクエスト81",
		--[82] = "FRクエスト82",
		--[83] = "FRクエスト83",
		--[84] = "FRクエスト84",
		--[85] = "FRクエスト85",
		--[86] = "FRクエスト86",
		--[87] = "FRクエスト87",
		--[88] = "FRクエスト88",
		--[89] = "FRクエスト89",
		--[90] = "FRクエスト90",
		--[91] = "FRクエスト91",
		--[92] = "FRクエスト92",
		--[93] = "FRクエスト93",
		--[94] = "FRクエスト94",
		--[95] = "FRクエスト95",
		--[96] = "FRクエスト96",
		--[97] = "FRクエスト97",
		--[99] = "FRクエスト99",
		[100] = "Voidwatch Ops: Border Crossing",
		[101] = "VW Op. #054: Elshimo List",
		[102] = "VW Op. #101: Detour to Zepwell",
		[103] = "VW Op. #115: Li'Telor Variant",
		[104] = "Skyward Ho, Voidwatcher!",
		--[106] = "FRクエスト106",
		--[107] = "FRクエスト107",
		--[108] = "FRクエスト108",
		--[109] = "FRクエスト109",
		--[110] = "FRクエスト110",
		--[111] = "FRクエスト111",
		--[112] = "FRクエスト112",
		--[113] = "FRクエスト113",
		--[114] = "FRクエスト114",
		--[115] = "FRクエスト115",
		--[116] = "FRクエスト116",
		--[117] = "FRクエスト117",
		--[118] = "FRクエスト118",
		--[119] = "FRクエスト119",
		--[120] = "FRクエスト120",
		--[121] = "FRクエスト121",
		--[122] = "FRクエスト122",
		--[123] = "FRクエスト123",
		--[124] = "FRクエスト124",
		--[125] = "FRクエスト125",
		--[126] = "FRクエスト126",
		--[127] = "FRクエスト127",
		
		--[128] = "The Sahagin's Key",
		[129] = "Forge Your Destiny",
		[130] = "Black Market",
		[131] = "Mama Mia",
		[132] = "Stop Your Whining",
		[133] = "+Trial by Water",
		[134] = "Everyone's Grudge",
		[135] = "Secret of the Damp Scroll",
		[136] = "The Sahagin's Stash",
		[137] = "It's Not Your Vault",
		[138] = "Like a Shining Subligar",
		[139] = "Like Shining Leggings",
		[140] = "The Sacred Katana",
		[141] = "Yomi Okuri",
		[142] = "A Thief in Norg!?",
		[143] = "20 in Pirate Years",
		[144] = "I'll Take the Big Box",
		[145] = "True Will",
		[146] = "The Potential Within",
		[147] = "Bugi Soden",
		[148] = "Trial-Size Trial by Water",
		[149] = "An Undying Pledge",
		--[150] = "FRクエスト150",
		--[151] = "FRクエスト151",
		--[152] = "FRクエスト152",
		--[153] = "FRクエスト153",
		--[154] = "FRクエスト154",
		--[155] = "FRクエスト155",
		--[156] = "FRクエスト156",
		--[157] = "FRクエスト157",
		--[158] = "FRクエスト158",
		--[159] = "FRクエスト159",
		[160] = "Wrath of the Opo-opos",
		[161] = "Wandering Souls",
		[162] = "Soul Searching",
		[163] = "Divine Might",
		[164] = "Divine Might",
		[165] = "Open Sesame",
		--[166] = "FRクエスト166",
		--[167] = "FRクエスト167",
		--[168] = "FRクエスト168",
		--[169] = "FRクエスト169",
		--[170] = "FRクエスト170",
		--[171] = "FRクエスト171",
		--[172] = "FRクエスト172",
		--[173] = "FRクエスト173",
		--[174] = "FRクエスト174",
		--[175] = "FRクエスト175",
		--[176] = "FRクエスト176",
		--[177] = "FRクエスト177",
		--[178] = "FRクエスト178",
		--[179] = "FRクエスト179",
		--[180] = "FRクエスト180",
		--[181] = "FRクエスト181",
		--[182] = "FRクエスト182",
		--[183] = "FRクエスト183",
		--[184] = "FRクエスト184",
		--[185] = "FRクエスト185",
		--[186] = "FRクエスト186",
		--[187] = "FRクエスト187",
		--[188] = "FRクエスト188",
		--[189] = "FRクエスト189",
		--[190] = "FRクエスト190",
		--[191] = "FRクエスト191",
		[192] = "Don't Forget the Antidote",
		[193] = "The Missing Piece",
		[194] = "+Trial by Wind",
		[195] = "The Kuftal Tour",
		[196] = "The Immortal Lu Shang",
		[197] = "Trial-Size Trial by Wind",
		[199] = "Chasing Dreams",
		[200] = "The Search for Goldmane",
		[201] = "Indomitable Spirit",
		[202] = "Fish Favors the Bold",
		[203] = "Thanks for All the Fish",
		--[204] = "FRクエスト204",
		--[205] = "FRクエスト205",
		--[206] = "FRクエスト206",
		--[207] = "FRクエスト207",
		--[208] = "FRクエスト208",
		--[209] = "FRクエスト209",
		--[210] = "FRクエスト210",
		--[211] = "FRクエスト211",
		--[212] = "FRクエスト212",
		--[213] = "FRクエスト213",
		--[214] = "FRクエスト214",
		--[215] = "FRクエスト215",
		--[216] = "FRクエスト216",
		--[217] = "FRクエスト217",
		--[218] = "FRクエスト218",
		--[219] = "FRクエスト219",
		--[220] = "FRクエスト220",
	},
	ahturhgan = {
		[0] = 'Keeping Notes',
		[1] = 'Arts And Crafts',
		[2] = 'Olduum',
		[3] = 'Got It All',
		[4] = 'Get The Picture',
		[5] = 'An Empty Vessel',
		[6] = 'Luck Of The Draw',
		[7] = 'No Strings Attached',
		[8] = 'Finding Faults',
		[9] = 'Give Peace A Chance',
		[10] = 'The Art Of War',
		--JPENTRIESORINVALID
		[12] = 'A Taste Of Honey',
		[13] = 'Such Sweet Sorrow',
		[14] = 'Fear Of The Dark Ii',
		[15] = 'Cook A Roon',
		[16] = 'The Die Is Cast',
		[17] = 'Two Horn The Savage',
		[18] = 'Totoroons Treasure Hunt',
		[19] = 'What Friends Are For',
		[20] = 'Rock Bottom',
		[21] = 'Beginnings',
		[22] = 'Omens',
		[23] = 'Transformations',
		[24] = 'Equipped For All Occasions',
		[25] = 'Navigating The Unfriendly Seas',
		[26] = 'Against All Odds',
		[27] = 'The Wayward Automaton',
		[28] = 'Operation Teatime',
		[29] = 'Puppetmaster Blues',
		[30] = 'Moment Of Truth',
		[31] = 'Three Men And A Closet',
		[32] = 'Five Seconds Of Fame',
		--JPENTRIESORINVALID
		[40] = 'The Beast Within',
		[41] = 'Breaking The Bonds Of Fate',
		--JPENTRIESORINVALID
		[43] = 'Saga Of The Skyserpent',
		[44] = 'Ode To The Serpents',
		[45] = 'When The Bow Breaks',
		[46] = 'Fist Of The People',
		[47] = 'Soothing Waters',
		[48] = 'Embers Of His Past',
		--JPENTRIESORINVALID
		[60] = 'The Prankster',
		[61] = 'Delivering The Goods',
		[62] = 'Vanishing Act',
		[63] = 'Striking A Balance',
		[64] = 'Not Meant To Be',
		[65] = 'Led Astray',
		[66] = 'Rat Race',
		[67] = 'The Prince And The Hopper',
		[68] = 'Vw Op 050 Aht Urgan Assault',
		[69] = 'Vw Op 068 Subterrainean Skirmish',
		[70] = 'An Imperial Heist',
		[71] = 'Duties Tasks And Deeds',
		[72] = 'Forging A New Myth',
		[73] = 'Coming Full Circle',
		[74] = 'Waking The Colossus',
		[75] = 'Divine Interference',
		[76] = 'The Rider Cometh',
		[77] = 'Unwavering Resolve',
		[78] = 'A Stygian Pact',
		--JPENTRIESORINVALID
		[90] = 'Promotion Private First Class',
		[91] = 'Promotion Superior Private',
		[92] = 'Promotion Lance Corporal',
		[93] = 'Promotion Corporal',
		[94] = 'Promotion Sergeant',
		[95] = 'Promotion Sergeant Major',
		[96] = 'Promotion Chief Sergeant',
		[97] = 'Promotion Second Lieutenant',
		[98] = 'Promotion First Lieutenant',
		[99] = 'Promotion Captain',
		--JPENTRIESORINVALID
		[101] = 'Scouting The Ashu Talif',
		[102] = 'Royal Painter Escort',
		[103] = 'Targeting The Captain'
	},
	crystalwar = {
		[0] = 'Lost In Translocation',
		[1] = 'Message On The Winds',
		[2] = 'The Weekly Adventurer',
		[3] = 'Healing Herbs',
		[4] = 'Redeeming Rocks',
		[5] = 'The Dawn Of Delectability',
		[6] = 'A Little Knowledge',
		[7] = 'The Fighting Fourth',
		[8] = 'Snake On The Plains',
		[9] = 'Steamed Rams',
		[10] = 'Seeing Spots',
		[11] = 'The Flipside Of Things',
		[12] = 'Better Part Of Valor',
		[13] = 'Fires Of Discontent',
		[14] = 'Hammering Hearts',
		[15] = 'Gifts Of The Griffon',
		[16] = 'Claws Of The Griffon',
		[17] = 'The Tigress Stirs',
		[18] = 'The Tigress Strikes',
		[19] = 'Light In The Darkness',
		[20] = 'Burden Of Suspicion',
		[21] = 'Evil At The Inlet',
		[22] = 'The Fumbling Friar',
		[23] = 'Requiem For The Departed',
		[24] = 'Boy And The Beast',
		[25] = 'Wrath Of The Griffon',
		[26] = 'The Lost Book',
		[27] = 'Knot Quite There',
		[28] = 'A Manifest Problem',
		[29] = 'Beans Ahoy',
		[30] = 'Beast From The East',
		--[31] = 'The Swarm',
		[32] = 'On Sabbatical',
		[33] = 'Downward Helix',
		[34] = 'Seeing Blood Red',
		[35] = 'Storm On The Horizon',
		[36] = 'Fire In The Hole',
		[37] = 'Perils Of The Griffon',
		[38] = 'In A Haze Of Glory',
		[39] = 'When One Man Is Not Enough',
		[40] = 'A Feast For Gnats',
		[41] = 'Say It With A Handbag',
		[42] = 'Quelling The Storm',
		[43] = 'Honor Under Fire',
		[44] = 'The Price Of Valor',
		[45] = 'Bonds That Never Die',
		[46] = 'The Long March North',
		[47] = 'The Forbidden Path',
		[48] = 'A Jewelers Lament',
		[49] = 'Beneath The Mask',
		[50] = 'What Price Loyalty',
		[51] = 'Songbirds In A Snowstorm',
		[52] = 'Blood Of Heroes',
		[53] = 'Sins Of The Mothers',
		[54] = 'Howl From The Heavens',
		[55] = 'Succor To The Sidhe',
		[56] = 'The Young And The Threadless',
		[57] = 'Son And Father',
		[58] = 'The Truth Lies Hid',
		[59] = 'Bonds Of Mythril',
		[60] = 'Chasing Shadows',
		[61] = 'Face Of The Future',
		[62] = 'Manifest Destiny',
		[63] = 'At Journeys End',
		[64] = 'Her Memories Homecoming Queen',
		[65] = 'Her Memories Old Bean',
		[66] = 'Her Memories The Faux Pas',
		[67] = 'Her Memories The Grave Resolve',
		[68] = 'Her Memories Operation Cupid',
		[69] = 'Her Memories Carnelian Footfalls',
		[70] = 'Her Memories Azure Footfalls',
		[71] = 'Her Memories Verdure Footfalls',
		[72] = 'Her Memories Of Malign Maladies',
		[73] = 'Champion Of The Dawn',
		[74] = 'The Dawn Also Rises',
		[75] = 'A Forbidden Reunion',
		[80] = 'Guardian Of The Void',
		[81] = 'Drafted By The Duchy',
		[82] = 'Battle On A New Front',
		[83] = 'Voidwalker Op 126',
		[84] = 'A Cait Calls',
		[85] = 'The Truth Is Out There',
		[86] = 'Redrafted By The Duchy',
		[87] = 'A New Menace',
		[88] = 'No Rest For The Weary',
		[89] = 'A World In Flux',
		[90] = 'Between A Rock And Rift',
		[91] = 'A Farewell To Felines',
		[92] = 'Third Tour Of Duchy',
		[93] = 'Glimmer Of Hope',
		[94] = 'Brace For The Unknown',
		[95] = 'Provenance',
		[96] = 'Crystal Guardian',
		[97] = 'Endings And Beginnings',
		--[98] = 'Ad Infinitum' -- non completable
	},
	campaign = {
		--[0] = '',
		[1] = 'Smokescreen I (S)',
		[2] = 'Smokescreen II (S)',
		[3] = 'Smokescreen III (S)',
		[4] = 'Smokescreen IV (S)',
		[5] = 'Smokescreen V (S)',
		[6] = 'Splitting Heirs (S)',
		[7] = 'Kinslayer: Baileys (S)',
		[8] = 'Kinslayer: Keep (S)',
		[9] = 'Fiat Lux (S)',
		--[10] = 'Campaign Operation',
		[11] = 'Pit Spider I (S)',
		[12] = 'Pit Spider II (S)',
		[13] = 'Pit Spider III (S)',
		[14] = 'By Light of Fire I (S)',
		--[15] = 'Campaign Operation',
		--[16] = 'Campaign Operation',
		--[17] = 'Campaign Operation',
		--[18] = 'Campaign Operation',
		--[19] = 'Campaign Operation',
		--[20] = 'Campaign Operation',
		[21] = 'Aegis Scream I (S)',
		[22] = 'Aegis Scream II (S)',
		[23] = 'Aegis Scream III (S)',
		[24] = 'Aegis Scream IV (S)',
		[25] = 'Aegis Scream V (S)',
		--[26] = 'Campaign Operation',
		--[27] = 'Campaign Operation',
		--[28] = 'Campaign Operation',
		--[29] = 'Campaign Operation',
		--[30] = 'Campaign Operation',
		[31] = 'Granite Rose I (S)',
		[32] = 'Granite Rose II (S)',
		[33] = 'Granite Rose III (S)',
		--[34] = 'Campaign Operation',
		--[35] = 'Campaign Operation',
		--[36] = 'Campaign Operation',
		--[37] = 'Campaign Operation',
		--[38] = 'Campaign Operation',
		--[39] = 'Campaign Operation',
		--[40] = 'Campaign Operation',
		[41] = 'Hawk Eye I (S)',
		[42] = 'Hawk Eye II (S)',
		[43] = 'Hawk Eye III (S)',
		[44] = 'Prying Eyes I (S)',
		[45] = 'Hawk Eye IV (S)',
		[46] = 'Deep Cover I (S)',
		[47] = 'Deep Cover II (S)',
		[48] = 'Deep Cover III (S)',
		[49] = 'Prying Eyes II (S)',
		--[50] = 'Campaign Operation',
		[51] = 'Slaughterhouse I (S)',
		[52] = 'Slaughterhouse II (S)',
		[53] = 'Slaughterhouse III (S)',
		[54] = 'Slaughterhouse IV (S)',
		[55] = 'Frozen Flame (S)',
		[56] = 'Bailey Borer (S)',
		--[57] = 'カンパニエミッション',
		--[58] = 'カンパニエミッション',
		--[59] = 'カンパニエミッション',
		--[60] = 'カンパニエミッション',
		[61] = 'Brave Dawn I (S)',
		[62] = 'Brave Dawn II (S)',
		[63] = 'Brave Dawn III (S)',
		--[64] = 'カンパニエミッション',
		--[65] = 'カンパニエミッション',
		--[66] = 'カンパニエミッション',
		--[67] = 'カンパニエミッション',
		--[68] = 'カンパニエミッション',
		--[69] = 'カンパニエミッション',
		--[70] = 'カンパニエミッション',
		[71] = 'Cut and Cauterize I (S)',
		[72] = 'Cut and Cauterize II (S)',
		[73] = 'Cut and Cauterize III (S)',
		--[74] = 'カンパニエミッション',
		--[75] = 'カンパニエミッション',
		--[76] = 'カンパニエミッション',
		--[77] = 'カンパニエミッション',
		--[78] = 'カンパニエミッション',
		--[79] = 'カンパニエミッション',
		--[80] = 'カンパニエミッション',
		[81] = 'Stock and Awe I (S)',
		[82] = 'Stock and Awe II (S)',
		[83] = 'Stock and Awe III (S)',
		[84] = 'Stock and Awe IV (S)',
		--[85] = 'カンパニエミッション',
		--[86] = 'カンパニエミッション',
		--[87] = 'カンパニエミッション',
		--[88] = 'カンパニエミッション',
		--[89] = 'カンパニエミッション',
		--[90] = 'カンパニエミッション',
		[91] = 'Materiel Storm I (S)',
		[92] = 'Materiel Storm II (S)',
		[93] = 'Materiel Storm III (S)',
		[94] = 'Materiel Storm IV (S)',
		--[95] = 'カンパニエミッション',
		[96] = 'Search and Seizure I (S)',
		--[97] = 'カンパニエミッション',
		--[98] = 'カンパニエミッション',
		--[99] = 'カンパニエミッション',
		--[100] = 'カンパニエミッション',
		[101] = 'Vanguard-X I (S)',
		[102] = 'Vanguard-X II (S)',
		[103] = 'Vanguard-X III (S)',
		[104] = 'Vanguard-X IV (S)',
		--[105] = 'カンパニエミッション',
		--[106] = 'カンパニエミッション',
		--[107] = 'カンパニエミッション',
		--[108] = 'カンパニエミッション',
		--[109] = 'カンパニエミッション',
		--[110] = 'カンパニエミッション',
		[111] = 'Crimson Domino I (S)',
		[112] = 'Crimson Domino II (S)',
		[113] = 'Crimson Domino III (S)',
		[114] = 'Bridge Too Far I (S)',
		[115] = 'Crimson Domino IV (S)',
		--[116] = 'カンパニエミッション',
		--[117] = 'カンパニエミッション',
		--[118] = 'カンパニエミッション',
		--[119] = 'カンパニエミッション',
		--[120] = 'カンパニエミッション',
		[121] = 'Crystal Fist I (S)',
		[122] = 'Crystal Fist II (S)',
		[123] = 'Crystal Fist III (S)',
		[124] = 'Crystal Fist IV (S)',
		--[125] = 'カンパニエミッション',
		--[126] = 'カンパニエミッション',
		--[127] = 'カンパニエミッション',
		--[128] = 'カンパニエミッション',
		--[129] = 'カンパニエミッション',
		--[130] = 'カンパニエミッション',
		[131] = 'Iron Anvil I (S)',
		[132] = 'Iron Anvil II (S)',
		[133] = 'Iron Anvil III (S)',
		[134] = 'Iron Anvil IV (S)',
		--[135] = 'カンパニエミッション',
		--[136] = 'カンパニエミッション',
		--[137] = 'カンパニエミッション',
		--[138] = 'カンパニエミッション',
		--[139] = 'カンパニエミッション',
		--[140] = 'カンパニエミッション',
		[141] = 'Streetsweeper I (S)',
		[142] = 'Streetsweeper II (S)',
		[143] = 'Streetsweeper III (S)',
		--[144] = 'カンパニエミッション',
		--[145] = 'カンパニエミッション',
		[146] = 'Delta Strike I (S)',
		[147] = 'Delta Strike II (S)',
		[148] = 'Delta Strike III (S)',
		--[149] = 'カンパニエミッション',
		--[150] = 'カンパニエミッション',
		[151] = 'Steel Resolve I (S)',
		[152] = 'Steel Resolve II (S)',
		[153] = 'Steel Resolve III (S)',
		[154] = 'Steel Resolve IV (S)',
		--[155] = 'カンパニエミッション',
		[156] = 'Magna Cache I (S)',
		[157] = 'Magna Cache II (S)',
		[158] = 'Magna Cache III (S)',
		[159] = 'Hazardous Materials (S)',
		--[160] = 'カンパニエミッション',
		--[161] = 'カンパニエミッション',
		--[162] = 'カンパニエミッション',
		--[163] = 'カンパニエミッション',
		--[164] = 'カンパニエミッション',
		--[165] = 'カンパニエミッション',
		--[166] = 'カンパニエミッション',
		--[167] = 'カンパニエミッション',
		--[168] = 'カンパニエミッション',
		--[169] = 'カンパニエミッション',
		--[170] = 'カンパニエミッション',
		[171] = 'Smokescreen I (B)',
		[172] = 'Smokescreen II (B)',
		[173] = 'Smokescreen III (B)',
		[174] = 'Smokescreen IV (B)',
		[175] = 'Smokescreen V (B)',
		[176] = 'Cracking Shells (B)',
		[177] = 'Kinslayer: Baileys (B)',
		[178] = 'Kinslayer: Keep (B)',
		[179] = 'Fiat Lux (B)',
		--[180] = 'カンパニエミッション',
		[181] = 'Pit Spider I (B)',
		[182] = 'Pit Spider II (B)',
		[183] = 'Pit Spider III (B)',
		[184] = 'By Light of Fire I (B)',
		--[185] = 'カンパニエミッション',
		--[186] = 'カンパニエミッション',
		--[187] = 'カンパニエミッション',
		--[188] = 'カンパニエミッション',
		--[189] = 'カンパニエミッション',
		--[190] = 'カンパニエミッション',
		[191] = 'Aegis Scream I (B)',
		[192] = 'Aegis Scream II (B)',
		[193] = 'Aegis Scream III (B)',
		[194] = 'Aegis Scream IV (B)',
		[195] = 'Aegis Scream V (B)',
		--[196] = 'カンパニエミッション',
		--[197] = 'カンパニエミッション',
		--[198] = 'カンパニエミッション',
		--[199] = 'カンパニエミッション',
		--[200] = 'カンパニエミッション',
		[201] = 'Granite Rose I (B)',
		[202] = 'Granite Rose II (B)',
		[203] = 'Granite Rose III (B)',
		--[204] = 'カンパニエミッション',
		--[205] = 'カンパニエミッション',
		--[206] = 'カンパニエミッション',
		--[207] = 'カンパニエミッション',
		--[208] = 'カンパニエミッション',
		--[209] = 'カンパニエミッション',
		--[210] = 'カンパニエミッション',
		[211] = 'Hawk Eye I (B)',
		[212] = 'Hawk Eye II (B)',
		[213] = 'Hawk Eye III (B)',
		[214] = 'Prying Eyes I (B)',
		[215] = 'Hawk Eye IV (B)',
		[216] = 'Deep Cover I (B)',
		[217] = 'Deep Cover II (B)',
		[218] = 'Deep Cover III (B)',
		[219] = 'Prying Eyes II (B)',
		--[220] = 'カンパニエミッション',
		[221] = 'Slaughterhouse I (B)',
		[222] = 'Slaughterhouse II (B)',
		[223] = 'Slaughterhouse III (B)',
		[224] = 'Slaughterhouse IV (B)',
		[225] = 'Frozen Flame (B)',
		[226] = 'Bailey Borer (B)',
		--[227] = 'カンパニエミッション',
		--[228] = 'カンパニエミッション',
		--[229] = 'カンパニエミッション',
		--[230] = 'カンパニエミッション',
		[231] = 'Brave Dawn I (B)',
		[232] = 'Brave Dawn II (B)',
		[233] = 'Brave Dawn III (B)',
		--[234] = 'カンパニエミッション',
		--[235] = 'カンパニエミッション',
		--[236] = 'カンパニエミッション',
		--[237] = 'カンパニエミッション',
		--[238] = 'カンパニエミッション',
		--[239] = 'カンパニエミッション',
		--[240] = 'カンパニエミッション',
		[241] = 'Cut and Cauterize I (B)',
		[242] = 'Cut and Cauterize II (B)',
		[243] = 'Cut and Cauterize III (B)',
		--[244] = 'カンパニエミッション',
		--[245] = 'カンパニエミッション',
		--[246] = 'カンパニエミッション',
		--[247] = 'カンパニエミッション',
		--[248] = 'カンパニエミッション',
		--[249] = 'カンパニエミッション',
		--[250] = 'カンパニエミッション',
		[251] = 'Stock and Awe I (B)',
		[252] = 'Stock and Awe II (B)',
		[253] = 'Stock and Awe III (B)',
		[254] = 'Stock and Awe IV (B)',
		--[255] = 'カンパニエミッション',
		--[256] = 'カンパニエミッション',
		--[257] = 'カンパニエミッション',
		--[258] = 'カンパニエミッション',
		--[259] = 'カンパニエミッション',
		--[260] = 'カンパニエミッション',
		[261] = 'Materiel Storm I (B)',
		[262] = 'Materiel Storm II (B)',
		[263] = 'Materiel Storm III (B)',
		[264] = 'Materiel Storm IV (B)',
		--[265] = 'カンパニエミッション',
		[266] = 'Search and Seizure I (B)',
		--[267] = 'カンパニエミッション',
		--[268] = 'カンパニエミッション',
		--[269] = 'カンパニエミッション',
		--[270] = 'カンパニエミッション',
		[271] = 'Vanguard-X I (B)',
		[272] = 'Vanguard-X II (B)',
		[273] = 'Vanguard-X III (B)',
		[274] = 'Vanguard-X IV (B)',
		--[275] = 'カンパニエミッション',
		--[276] = 'カンパニエミッション',
		--[277] = 'カンパニエミッション',
		--[278] = 'カンパニエミッション',
		--[279] = 'カンパニエミッション',
		--[280] = 'カンパニエミッション',
		[281] = 'Crimson Domino I (B)',
		[282] = 'Crimson Domino II (B)',
		[283] = 'Crimson Domino III (B)',
		[284] = 'Bridge Too Far I (B)',
		[285] = 'Crimson Domino IV (B)',
		--[286] = 'カンパニエミッション',
		--[287] = 'カンパニエミッション',
		--[288] = 'カンパニエミッション',
		--[289] = 'カンパニエミッション',
		--[290] = 'カンパニエミッション',
		[291] = 'Crystal Fist I (B)',
		[292] = 'Crystal Fist II (B)',
		[293] = 'Crystal Fist III (B)',
		[294] = 'Crystal Fist IV (B)',
		--[295] = 'カンパニエミッション',
		--[296] = 'カンパニエミッション',
		--[297] = 'カンパニエミッション',
		--[298] = 'カンパニエミッション',
		--[299] = 'カンパニエミッション',
		--[300] = 'カンパニエミッション',
		[301] = 'Iron Anvil I (B)',
		[302] = 'Iron Anvil II (B)',
		[303] = 'Iron Anvil III (B)',
		[304] = 'Iron Anvil IV (B)',
		--[305] = 'カンパニエミッション',
		--[306] = 'カンパニエミッション',
		--[307] = 'カンパニエミッション',
		--[308] = 'カンパニエミッション',
		--[309] = 'カンパニエミッション',
		--[310] = 'カンパニエミッション',
		[311] = 'Streetsweeper I (B)',
		[312] = 'Streetsweeper II (B)',
		[313] = 'Streetsweeper III (B)',
		--[314] = 'カンパニエミッション',
		--[315] = 'カンパニエミッション',
		[316] = 'Delta Strike I (B)',
		[317] = 'Delta Strike II (B)',
		[318] = 'Delta Strike III (B)',
		--[319] = 'カンパニエミッション',
		--[320] = 'カンパニエミッション',
		[321] = 'Steel Resolve I (B)',
		[322] = 'Steel Resolve II (B)',
		[323] = 'Steel Resolve III (B)',
		[324] = 'Steel Resolve IV (B)',
		--[325] = 'カンパニエミッション',
		[326] = 'Magna Cache I (B)',
		[327] = 'Magna Cache II (B)',
		[328] = 'Magna Cache III (B)',
		[329] = 'Hazardous Materials (B)',
		--[330] = 'カンパニエミッション',
		--[331] = 'カンパニエミッション',
		--[332] = 'カンパニエミッション',
		--[333] = 'カンパニエミッション',
		--[334] = 'カンパニエミッション',
		--[335] = 'カンパニエミッション',
		--[336] = 'カンパニエミッション',
		--[337] = 'カンパニエミッション',
		--[338] = 'カンパニエミッション',
		--[339] = 'カンパニエミッション',
		--[340] = 'カンパニエミッション',
		[341] = 'Smokescreen I (W)',
		[342] = 'Smokescreen II (W)',
		[343] = 'Smokescreen III (W)',
		[344] = 'Smokescreen IV (W)',
		[345] = 'Smokescreen V (W)',
		[346] = 'Plucking Wings (W)',
		[347] = 'Kinslayer: Baileys (W)',
		[348] = 'Kinslayer: Keep (W)',
		[349] = 'Fiat Lux (W)',
		--[350] = 'カンパニエミッション',
		[351] = 'Pit Spider I (W)',
		[352] = 'Pit Spider II (W)',
		[353] = 'Pit Spider III (W)',
		[354] = 'By Light of Fire I (W)',
		--[355] = 'カンパニエミッション',
		--[356] = 'カンパニエミッション',
		--[357] = 'カンパニエミッション',
		--[358] = 'カンパニエミッション',
		--[359] = 'カンパニエミッション',
		--[360] = 'カンパニエミッション',
		[361] = 'Aegis Scream I (W)',
		[362] = 'Aegis Scream II (W)',
		[363] = 'Aegis Scream III (W)',
		[364] = 'Aegis Scream IV (W)',
		[365] = 'Aegis Scream V (W)',
		--[366] = 'カンパニエミッション',
		--[367] = 'カンパニエミッション',
		--[368] = 'カンパニエミッション',
		--[369] = 'カンパニエミッション',
		--[370] = 'カンパニエミッション',
		[371] = 'Granite Rose I (W)',
		[372] = 'Granite Rose II (W)',
		[373] = 'Granite Rose III (W)',
		--[374] = 'カンパニエミッション',
		--[375] = 'カンパニエミッション',
		--[376] = 'カンパニエミッション',
		--[377] = 'カンパニエミッション',
		--[378] = 'カンパニエミッション',
		--[379] = 'カンパニエミッション',
		--[380] = 'カンパニエミッション',
		[381] = 'Hawk Eye I (W)',
		[382] = 'Hawk Eye II (W)',
		[383] = 'Hawk Eye III (W)',
		[384] = 'Prying Eyes I (W)',
		[385] = 'Hawk Eye IV (W)',
		[386] = 'Deep Cover I (W)',
		[387] = 'Deep Cover II (W)',
		[388] = 'Deep Cover III (W)',
		[389] = 'Prying Eyes II (W)',
		--[390] = 'カンパニエミッション',
		[391] = 'Slaughterhouse I (W)',
		[392] = 'Slaughterhouse II (W)',
		[393] = 'Slaughterhouse III (W)',
		[394] = 'Slaughterhouse IV (W)',
		[395] = 'Frozen Flame (W)',
		[396] = 'Bailey Borer (W)',
		--[397] = 'カンパニエミッション',
		--[398] = 'カンパニエミッション',
		--[399] = 'カンパニエミッション',
		--[400] = 'カンパニエミッション',
		[401] = 'Brave Dawn I (W)',
		[402] = 'Brave Dawn II (W)',
		[403] = 'Brave Dawn III (W)',
		--[404] = 'カンパニエミッション',
		--[405] = 'カンパニエミッション',
		--[406] = 'カンパニエミッション',
		--[407] = 'カンパニエミッション',
		--[408] = 'カンパニエミッション',
		--[409] = 'カンパニエミッション',
		--[410] = 'カンパニエミッション',
		[411] = 'Cut and Cauterize I (W)',
		[412] = 'Cut and Cauterize II (W)',
		[413] = 'Cut and Cauterize III (W)',
		--[414] = 'カンパニエミッション',
		--[415] = 'カンパニエミッション',
		--[416] = 'カンパニエミッション',
		--[417] = 'カンパニエミッション',
		--[418] = 'カンパニエミッション',
		--[419] = 'カンパニエミッション',
		--[420] = 'カンパニエミッション',
		[421] = 'Stock and Awe I (W)',
		[422] = 'Stock and Awe II (W)',
		[423] = 'Stock and Awe III (W)',
		[424] = 'Stock and Awe IV (W)',
		--[425] = 'カンパニエミッション',
		--[426] = 'カンパニエミッション',
		--[427] = 'カンパニエミッション',
		--[428] = 'カンパニエミッション',
		--[429] = 'カンパニエミッション',
		--[430] = 'カンパニエミッション',
		[431] = 'Materiel Storm I (W)',
		[432] = 'Materiel Storm II (W)',
		[433] = 'Materiel Storm III (W)',
		[434] = 'Materiel Storm IV (W)',
		--[435] = 'カンパニエミッション',
		[436] = 'Search and Seizure I (W)',
		--[437] = 'カンパニエミッション',
		--[438] = 'カンパニエミッション',
		--[439] = 'カンパニエミッション',
		--[440] = 'カンパニエミッション',
		[441] = 'Vanguard-X I (W)',
		[442] = 'Vanguard-X II (W)',
		[443] = 'Vanguard-X III (W)',
		[444] = 'Vanguard-X IV (W)',
		--[445] = 'カンパニエミッション',
		--[446] = 'カンパニエミッション',
		--[447] = 'カンパニエミッション',
		--[448] = 'カンパニエミッション',
		--[449] = 'カンパニエミッション',
		--[450] = 'カンパニエミッション',
		[451] = 'Crimson Domino I (W)',
		[452] = 'Crimson Domino II (W)',
		[453] = 'Crimson Domino III (W)',
		[454] = 'Bridge Too Far I (W)',
		[455] = 'Crimson Domino IV (W)',
		--[456] = 'カンパニエミッション',
		--[457] = 'カンパニエミッション',
		--[458] = 'カンパニエミッション',
		--[459] = 'カンパニエミッション',
		--[460] = 'カンパニエミッション',
		[461] = 'Crystal Fist I (W)',
		[462] = 'Crystal Fist II (W)',
		[463] = 'Crystal Fist III (W)',
		[464] = 'Crystal Fist IV (W)',
		--[465] = 'カンパニエミッション',
		--[466] = 'カンパニエミッション',
		--[467] = 'カンパニエミッション',
		--[468] = 'カンパニエミッション',
		--[469] = 'カンパニエミッション',
		--[470] = 'カンパニエミッション',
		[471] = 'Iron Anvil I (W)',
		[472] = 'Iron Anvil II (W)',
		[473] = 'Iron Anvil III (W)',
		[474] = 'Iron Anvil IV (W)',
		--[475] = 'カンパニエミッション',
		--[476] = 'カンパニエミッション',
		--[477] = 'カンパニエミッション',
		--[478] = 'カンパニエミッション',
		--[479] = 'カンパニエミッション',
		--[480] = 'カンパニエミッション',
		[481] = 'Streetsweeper I (W)',
		[482] = 'Streetsweeper II (W)',
		[483] = 'Streetsweeper III (W)',
		--[484] = 'カンパニエミッション',
		--[485] = 'カンパニエミッション',
		[486] = 'Delta Strike I (W)',
		[487] = 'Delta Strike II (W)',
		[488] = 'Delta Strike III (W)',
		--[489] = 'カンパニエミッション',
		--[490] = 'カンパニエミッション',
		[491] = 'Steel Resolve I (W)',
		[492] = 'Steel Resolve II (W)',
		[493] = 'Steel Resolve III (W)',
		[494] = 'Steel Resolve IV (W)',
		--[495] = 'カンパニエミッション',
		[496] = 'Magna Cache I (W)',
		[497] = 'Magna Cache II (W)',
		[498] = 'Magna Cache III (W)',
		[499] = 'Hazardous Materials (W)',
		--[500] = 'カンパニエミッション',
		--[501] = 'カンパニエミッション',
		--[502] = 'カンパニエミッション',
		--[503] = 'カンパニエミッション',
		--[504] = 'カンパニエミッション',
		--[505] = 'カンパニエミッション',
		--[506] = 'カンパニエミッション',
		--[507] = 'カンパニエミッション',
		--[508] = 'カンパニエミッション',
		--[509] = 'カンパニエミッション',
		--[510] = 'カンパニエミッション',
		--[511] = 'カンパニエミッション',
	},
	abyssea = {
		[0] = 'Catering Capers',
		[1] = 'Gift of Light',
		[2] = 'Fear of the Dark III',
		[3] = 'An Eye for Revenge',
		[4] = 'Unbreak His Heart',
		[5] = 'Explosive Endeavors',
		[6] = 'The Angling Armorer',
		[7] = 'Water of Life',
		[8] = 'Out of Touch',
		[9] = 'Lost Memories',
		[10] = 'Hope Blooms on the Battlefield',
		[11] = 'Of Malnourished Martellos',
		[12] = 'Rose on the Heath',
		[13] = 'Full-of-Himself Alchemist',
		[14] = 'The Walking Wounded',
		[15] = 'Shady Business Redux',
		[16] = 'Addled Mind, Undying Dreams',
		[17] = 'The Soul of the Matter',
		[18] = 'Secret Agent Man',
		[19] = 'Playing Paparazzi',
		[20] = 'His Box, His Beloved',
		[21] = 'Weapons, Not Worries',
		[22] = 'Cleansing the Canyon',
		[23] = 'Savory Salvation',
		[24] = 'Bringing Down the Mountain',
		[25] = 'A Sterling Specimen',
		[26] = 'For Love of a Daughter',
		[27] = 'Sisters in Crime',
		[28] = 'When Good Cardians Go Bad',
		[29] = 'Tangling with Tongue-twisters',
		[30] = 'A Ward to End All Wards',
		[31] = 'The Boxwatcher\'s Behest',
		[32] = 'His Bridge, His Beloved',
		[33] = 'Bad Communication',
		[34] = 'Family Ties',
		[35] = 'Aqua Pura',
		[36] = 'Aqua Puraga',
		[37] = 'Whither the Whisker',
		[38] = 'Scattered Shells, Scattered Mind',
		[39] = 'Wayward Wares',
		[40] = 'Looking for Lookouts',
		[41] = 'Flown the Coop',
		[42] = 'Threadbare Tribulations',
		[43] = 'An Offer You Can\'t Refuse',
		[44] = 'Something in the Air',
		[45] = 'An Acrididaen Anodyne',
		[46] = 'Hazy Prospects',
		[47] = 'For Want of a Pot',
		[48] = 'Missing in Action',
		[49] = 'I Dream of Flowers',
		[50] = 'Destiny Odyssey',
		[51] = 'Unidentified Research Object',
		[52] = 'Cookbook of Hope Restoring',
		[53] = 'Smoke over the Coast',
		[54] = 'Soil and Green',
		[55] = 'Dropping the Bomb',
		[56] = 'Wanted: Medical Supplies',
		[57] = 'Voices from Beyond',
		[58] = 'Benevolence Lost',
		[59] = 'Brugaire\'s Ambition',
		[60] = 'Chocobo Panic',
		[61] = 'The Egg Enthusiast',
		[62] = 'Getting Lucky',
		[63] = 'Her Father\'s Legacy',
		[64] = 'The Mysterious Head Patrol',
		[65] = 'Master Missing, Master Missed',
		[66] = 'The Perils of Kororo',
		[67] = 'Let There Be Light',
		[68] = 'Look Out Below',
		[69] = 'Home, Home on the Range',
		[70] = 'Imperial Espionage',
		[71] = 'Imperial Espionage II',
		[72] = 'Boreal Blossoms',
		[73] = 'Brothers in Arms',
		[74] = 'Scouts Astray',
		[75] = 'Frozen Flame Redux',
		[76] = 'Slip Slidin\' Away',
		[77] = 'Classrooms Without Borders',
		[78] = 'The Secret Ingredient',
		[79] = 'Help Not Wanted',
		[80] = 'The Titus Touch',
		[81] = 'Slacking Subordinates',
		[82] = 'Motherly Love',
		[83] = 'Look to the Sky',
		[84] = 'The Unmarked Tomb',
		[85] = 'Proof of the Lion',
		[86] = 'Brygid the Stylist Strikes Back',
		[87] = 'Dominion Op #01 (Altepa)',
		[88] = 'Dominion Op #02 (Altepa)',
		[89] = 'Dominion Op #03 (Altepa)',
		[90] = 'Dominion Op #04 (Altepa)',
		[91] = 'Dominion Op #05 (Altepa)',
		[92] = 'Dominion Op #06 (Altepa)',
		[93] = 'Dominion Op #07 (Altepa)',
		[94] = 'Dominion Op #08 (Altepa)',
		[95] = 'Dominion Op #09 (Altepa)',
		[96] = 'Dominion Op #10 (Altepa)',
		[97] = 'Dominion Op #11 (Altepa)',
		[98] = 'Dominion Op #12 (Altepa)',
		[99] = 'Dominion Op #13 (Altepa)',
		[100] = 'Dominion Op #14 (Altepa)',
		[101] = 'Dominion Op #01 (Uleguerand)',
		[102] = 'Dominion Op #02 (Uleguerand)',
		[103] = 'Dominion Op #03 (Uleguerand)',
		[104] = 'Dominion Op #04 (Uleguerand)',
		[105] = 'Dominion Op #05 (Uleguerand)',
		[106] = 'Dominion Op #06 (Uleguerand)',
		[107] = 'Dominion Op #07 (Uleguerand)',
		[108] = 'Dominion Op #08 (Uleguerand)',
		[109] = 'Dominion Op #09 (Uleguerand)',
		[110] = 'Dominion Op #10 (Uleguerand)',
		[111] = 'Dominion Op #11 (Uleguerand)',
		[112] = 'Dominion Op #12 (Uleguerand)',
		[113] = 'Dominion Op #13 (Uleguerand)',
		[114] = 'Dominion Op #14 (Uleguerand)',
		[115] = 'Dominion Op #01 (Grauberg)',
		[116] = 'Dominion Op #02 (Grauberg)',
		[117] = 'Dominion Op #03 (Grauberg)',
		[118] = 'Dominion Op #04 (Grauberg)',
		[119] = 'Dominion Op #05 (Grauberg)',
		[120] = 'Dominion Op #06 (Grauberg)',
		[121] = 'Dominion Op #07 (Grauberg)',
		[122] = 'Dominion Op #08 (Grauberg)',
		[123] = 'Dominion Op #09 (Grauberg)',
		[124] = 'Ward Warden I (Attohwa)',
		[125] = 'Ward Warden I (Misareaux)',
		[126] = 'Ward Warden I (Vunkerl)',
		[127] = 'Ward Warden II (Attohwa)',
		[128] = 'Ward Warden II (Misareaux)',
		[129] = 'Ward Warden II (Vunkerl)',
		[130] = 'Desert Rain I (Attohwa)',
		[131] = 'Desert Rain I (Misareaux)',
		[132] = 'Desert Rain I (Vunkerl)',
		[133] = 'Desert Rain II (Attohwa)',
		[134] = 'Desert Rain II (Misareaux)',
		[135] = 'Desert Rain II (Vunkerl)',
		[136] = 'Crimson Carpet I (Attohwa)',
		[137] = 'Crimson Carpet I (Misareaux)',
		[138] = 'Crimson Carpet I (Vunkerl)',
		[139] = 'Crimson Carpet II (Attohwa)',
		[140] = 'Crimson Carpet II (Misareaux)',
		[141] = 'Crimson Carpet II (Vunkerl)',
		[142] = 'Refuel and Replenish (La Theine)',
		[143] = 'Refuel and Replenish (Konschtat)',
		[144] = 'Refuel and Replenish (Tahrongi)',
		[145] = 'Refuel and Replenish (Attohwa)',
		[146] = 'Refuel and Replenish (Misareaux)',
		[147] = 'Refuel and Replenish (Vunkerl)',
		[148] = 'Refuel and Replenish (Altepa)',
		[149] = 'Refuel and Replenish (Uleguerand)',
		[150] = 'Refuel and Replenish (Grauberg)',
		[151] = 'A Mightier Martello (La Theine)',
		[152] = 'A Mightier Martello (Konschtat)',
		[153] = 'A Mightier Martello (Tahrongi)',
		[154] = 'A Mightier Martello (Attohwa)',
		[155] = 'A Mightier Martello (Misareaux)',
		[156] = 'A Mightier Martello (Vunkerl)',
		[157] = 'A Mightier Martello (Altepa)',
		[158] = 'A Mightier Martello (Uleguerand)',
		[159] = 'A Mightier Martello (Grauberg)',
		[160] = 'A Journey Begins',
		[161] = 'The Truth Beckons',
		[162] = 'Dawn of Death',
		[163] = 'A Goldstruck Gigas',
		[164] = 'To Paste a Peiste',
		[165] = 'Megadrile Menace',
		[166] = 'The Forbidden Frontier',
		[167] = 'First Contact',
		[168] = 'An Officer and a Pirate',
		[169] = 'Heart of Madness',
		[170] = 'Tenuous Existence',
		[171] = 'Champions of Abyssea',    
		[172] = 'The Beast of Bastore',
		[173] = 'A Delectable Demon',
		[174] = 'A Fluttery Fiend',
		[175] = 'Scars of Abyssea',
		[176] = 'A Beaked Blusterer',
		[177] = 'A Man-eating Mite',
		[178] = 'An Ulcerous Uragnite',
		[179] = 'Heroes of Abyssea',
		[180] = 'A Sea Dog\'s Summons',
		[181] = 'Death and Rebirth',
		[182] = 'Emissaries of God',
		[183] = 'Beneath a Blood-red Sky',
		[184] = 'The Wyrm God',
		[185] = 'Meanwhile, Back on Abyssea',
		--[186] = 'A Moonlight Requite', -- non completable
		[187] = 'Dominion Op #10 (Grauberg)',
		[188] = 'Dominion Op #11 (Grauberg)',
		[189] = 'Dominion Op #12 (Grauberg)',
		[190] = 'Dominion Op #13 (Grauberg)',
		[191] = 'Dominion Op #14 (Grauberg)',
	},
	adoulin = {
		[0] = "Twitherym Dust",
		[1] = "To Catch a Predator",
		[2] = "Empty Nest",
		[5] = "Don't Clam Up on Me Now",
		[6] = "Hop to It",
		[9] = "Boiling Over",
		[10] = "Poisoning the Well",
		[12] = "Unsullied Lands",
		[16] = "No Rime Like the Present",
		[18] = "A Geothermal Expedition",
		[22] = "Endeavoring to Awaken",
		[23] = "Forging New Bonds",
		[24] = "Legacies Lost and Found",
		[25] = "Destiny's Device",
		[26] = "+Granddaddy Dearest",
		[27] = "Wayward Waypoints",
		[28] = "One Good Turn...",
		[29] = "F.A.I.L.ure Is Not an Option",
		[30] = "Order Up",
		[31] = "+It Never Goes Out of Style",
		[32] = "Water, Water, Everywhere",
		[33] = "Dirt Cheap",
		[34] = "+Flower Power",
		[35] = "Elementary, My Dear Sylvie",
		[36] = "For Whom the Bell Tolls",
		[37] = "The Bloodline of Zacariah",
		[38] = "The Communion",
		
		-- mog garden (taken from 'Other' DAT File id from 1039 to 1049
		[39] = "Full Fields",
		[40] = "Green Groves",
		[41] = "Mining Missive",
		[42] = "Pond Probing",
		[43] = "Coastal Chaos",
		[44] = "Seed Sowing",
		[45] = "Flotsam Finding",
		[47] = "Courtesy Crustacean",
		[48] = "Trinket for the Tyrant",
		[49] = "Hypnotic Hospitality",
		
		[46] = "Flavors of Our Lives",
		[50] = "Western Waypoints, Ho!",
		[51] = "Wes...Eastern Waypoints, Ho!",
		[53] = "Grind to Sawdust",
		[54] = "Breaking the Ice",
		[55] = "I'm on a Boat",
		[56] = "A Stone's Throw Away",
		[57] = "Hide and Go Peak",
		[58] = "The Whole Place Is Abuzz",
		[59] = "Orobon Appetit",
		[60] = "Talk About Wrinkly Skin",
		[61] = "No Love Lost",
		[62] = "Did You Feel That?",
		[70] = "Don't Ever Leaf Me",
		[71] = "Keep Your Bloomers On, Erisa",
		[72] = "Scaredy-Cats",
		[73] = "Raptor Rapture",
		[74] = "Exotic Delicacies",
		[75] = "A Pioneer's Best (Imaginary) Friend",
		[76] = "Hunger Strikes",
		[77] = "The Old Man and the Harpoon",
		[78] = "A Certain Substitute Patrolman",
		[79] = "+It Sets My Heart Aflutter",
		[82] = "Transporting",
		[84] = "The Starving",
		[85] = "Fertile Ground",
		[88] = "\"Always more,\" Quoth the Ravenous",
		[89] = "Meg-alomaniac",
		[91] = "The Longest Way Round...",
		[93] = "+A Good Pair of Crocs",
		[94] = "+Cafe...teria",
		[96] = "+A Shot in the Dark",
		[100] = "Open the Floodgates",
		[102] = "No Laughing Matter",
		[103] = "All the Way to the Bank",
		[104] = "To Laugh Is to Love",
		[105] = "A Barrel of Laughs",
		[108] = "Vegetable Vegetable Revolution",
		[109] = "Vegetable Vegetable Evolution",
		[110] = "Vegetable Vegetable Crisis",
		[111] = "Vegetable Vegetable Frustration",
		[114] = "A Thirst for the Ages",
		[115] = "A Thirst for the Eons",
		[116] = "A Thirst for Eternity",
		[117] = "A Thirst Before Time",
		[118] = "Dances with Luopans",
		[119] = "Children of the Rune",
		[120] = "Flowers for Svenja",
		[121] = "Thorn in the Side",
		[122] = "Do Not Go Into the Light",
		[123] = "Velkkovert Operations",
		[124] = "Hypocritical Oath",
		[125] = "The Good, the Bad, the Clement",
		[126] = "Lerene's Lament",
		[127] = "The Secret to Success",
		[128] = "No Mercy for the Wicked",
		[129] = "Mistress of Ceremonies",
		[131] = "Saved by the Bell",
		[132] = "Quiescence",
		[133] = "Sick and Tired",
		[134] = "Geomancerrific",
		[135] = "Rune Fencing the Night Away",
		[136] = "The Weatherspoon Inquisition",
		[137] = "Eye of the Beholder",
		[138] = "The Curious Case of Melvien",
		[139] = "Not-So-Clean Bill",
		[140] = "In the Land of the Blind",
		[141] = "The Weatherspoon War",
		[142] = "Treasures of the Earth",
		[143] = "Epiphany",
		[144] = "The Silent Forest",
		[145] = "+Winds of Eternity",
	},
	coalition = {
		[0] = 'Procure: Ceizak Battlegrounds',
		[1] = 'Procure: Foret de Hennetiel',
		[2] = 'Procure: Morimar Basalt Fields',
		[3] = 'Procure: Yorcia Weald',
		[4] = 'Procure: Marjami Ravine',
		[5] = 'Procure: Kamihr Drifts',
		[6] = 'Procure: Cirdas Caverns',
		[7] = 'Procure: Outer Ra\'Kaznar',
		[8] = 'Clear: Ceizak Battlegrounds',
		[9] = 'Clear: Foret de Hennetiel',
		[10] = 'Clear: Morimar Basalt Fields',
		[11] = 'Clear: Yorcia Weald',
		[12] = 'Clear: Marjami Ravine',
		[13] = 'Clear: Kamihr Drifts',
		[14] = 'Clear: Cirdas Caverns',
		[15] = 'Clear: Outer Ra\'Kaznar',
		--[16] = 'Provide: Foret de Hennetiel',
		--[17] = 'Provide: Morimar Basalt Fields',
		--[18] = 'Provide: Yorcia Weald',
		--[19] = 'Provide: Marjami Ravine',
		--[20] = 'Provide: Kamihr Drifts',
		[21] = 'Deliver: Foret de Hennetiel',
		[22] = 'Deliver: Morimar Basalt Fields',
		[23] = 'Deliver: Yorcia Weald',
		[24] = 'Deliver: Marjami Ravine',
		[25] = 'Deliver: Kamihr Drifts',
		[26] = 'Support: Ceizak Battlegrounds',
		[27] = 'Support: Foret de Hennetiel',
		[28] = 'Support: Morimar Basalt Fields',
		[29] = 'Support: Yorcia Weald',
		[30] = 'Support: Marjami Ravine',
		[31] = 'Support: Kamihr Drifts',
		[32] = 'Gather: Rala Waterways',
		[33] = 'Gather: Ceizak Battlegrounds',
		[34] = 'Gather: Yahse Hunting Grounds',
		[35] = 'Gather: Foret de Hennetiel',
		[36] = 'Gather: Morimar Basalt Fields',
		[37] = 'Gather: Yorcia Weald',
		[38] = 'Gather: Marjami Ravine',
		[39] = 'Gather: Kamihr Drifts',
		[40] = 'Gather: Sih Gates',
		[41] = 'Gather: Moh Gates',
		[42] = 'Gather: Cirdas Caverns',
		[43] = 'Gather: Dho Gates',
		[44] = 'Gather: Woh Gates',
		[45] = 'Gather: Outer Ra\'Kaznar',
		[46] = 'Gather: Ra\'Kaznar Inner Court',
		--[47] = 'Gather:',
		[48] = 'Survey: Ceizak Battlegrounds',
		[49] = 'Survey: Foret de Hennetiel',
		[50] = 'Survey: Morimar Basalt Fields',
		[51] = 'Survey: Yorcia Weald',
		[52] = 'Survey: Marjami Ravine',
		[53] = 'Survey: Kamihr Drifts',
		[54] = 'Survey: Sih Gates',
		[55] = 'Survey: Cirdas Caverns',
		[56] = 'Survey: Dho Gates',
		[57] = 'Analyze: Foret de Hennetiel',
		[58] = 'Analyze: Morimar Basalt Fields',
		[59] = 'Analyze: Yorcia Weald',
		[60] = 'Analyze: Marjami Ravine',
		[61] = 'Analyze: Kamihr Drifts',
		[62] = 'Analyze: Cirdas Caverns',
		[63] = 'Analyze: Outer Ra\'Kaznar',
		[64] = 'Preserve: Ceizak Battlegrounds',
		[65] = 'Preserve: Yahse Hunting Grounds',
		[66] = 'Preserve: Foret de Hennetiel',
		[67] = 'Preserve: Morimar Basalt Fields',
		[68] = 'Preserve: Yorcia Weald',
		[69] = 'Preserve: Marjami Ravine',
		[70] = 'Preserve: Kamihr Drifts',
		[71] = 'Preserve: Cirdas Caverns',
		[72] = 'Preserve: Outer Ra\'Kaznar',
		[73] = 'Patrol: Rala Waterways',
		[74] = 'Patrol: Sih Gates',
		[75] = 'Patrol: Moh Gates',
		[76] = 'Patrol: Cirdas Caverns',
		[77] = 'Patrol: Dho Gates',
		[78] = 'Patrol: Woh Gates',
		[79] = 'Patrol: Outer Ra\'Kaznar',
		[80] = 'Recover: Ceizak Battlegrounds',
		[81] = 'Recover: Foret de Hennetiel',
		[82] = 'Recover: Morimar Basalt Fields',
		[83] = 'Recover: Yorcia Weald',
		[84] = 'Recover: Marjami Ravine',
		[85] = 'Recover: Kamihr Drifts',
		[86] = 'Research: Rala Waterways',
		[87] = 'Research: Ceizak Battlegrounds',
		[88] = 'Research: Foret de Hennetiel',
		[89] = 'Research: Morimar Basalt Fields',
		[90] = 'Research: Yorcia Weald',
		[91] = 'Research: Marjami Ravine',
		[92] = 'Research: Kamihr Drifts',
		[93] = 'Boost: Foret de Hennetiel',
		[94] = 'Boost: Marjami Ravine',
		[95] = 'Boost: Kamihr Drifts',
	},
	sandoriamissions = {
		[0] = "Smash the Orcish Scouts",
		[1] = "Bat Hunt",
		[2] = "Save the Children",
		[3] = "The Rescue Drill",
		[4] = "The Davoi Report",
		[5] = "Journey Abroad",
		--[6] = "Journey to Bastok",
		--[7] = "Journey to Windurst",
		--[8] = "Journey to Bastok",
		--[9] = "Journey to Windurst",
		[10] = "Infiltrate Davoi",
		[11] = "The Crystal Spring",
		[12] = "Appointment to Jeuno",
		[13] = "Magicite",
		[14] = "The Ruins of Fei'Yin",
		[15] = "The Shadow Lord",
		[16] = "Leaute's Last Wishes",
		[17] = "Ranperre's Final Rest",
		[18] = "Prestige of the Papsque",
		[19] = "The Secret Weapon",
		[20] = "Coming of Age",
		[21] = "Lightbringer",
		[22] = "Breaking Barriers",
		[23] = "The Heir to the Light",
	},
	bastokmissions = {
		[0] = "The Zeruhn Report",
		[1] = "A Geological Survey",
		[2] = "Fetichism",
		[3] = "The Crystal Line",
		[4] = "Wading Beasts",
		[5] = "The Emissary",
		--[6] = "The Emissary (San d'Oria)",
		--[7] = "The Emissary (Windurst)",
		--[8] = "The Emissary (San d'Oria)",
		--[9] = "The Emissary (Windurst)",
		[10] = "The Four Musketeers",
		[11] = "To the Forsaken Mines",
		[12] = "Jeuno",
		[13] = "Magicite",
		[14] = "Darkness Rising",
		[15] = "Xarcabard, Land of Truths",
		[16] = "Return of the Talekeeper",
		[17] = "The Pirates' Cove",
		[18] = "The Final Image",
		[19] = "On My Way",
		[20] = "The Chains That Bind Us",
		[21] = "Enter the Talekeeper",
		[22] = "The Salt of the Earth",
		[23] = "Where Two Paths Converge",
		--[24] = "BSミッション24",
		--[25] = "BSミッション25",
		--[26] = "BSミッション26",
		--[27] = "BSミッション27",
		--[28] = "BSミッション28",
		--[29] = "BSミッション29",
		--[30] = "BSミッション30",
		--[31] = "BSミッション31",
		--[32] = "BSミッション32",
		--[33] = "BSミッション33",
		--[34] = "BSミッション34",
		--[35] = "BSミッション35",
		--[36] = "BSミッション36",
		--[37] = "BSミッション37",
		--[38] = "BSミッション38",
		--[39] = "BSミッション39",
		--[40] = "BSミッション40",
		--[41] = "BSミッション41",
		--[42] = "BSミッション42",
		--[43] = "BSミッション43",
		--[44] = "BSミッション44",
		--[45] = "BSミッション45",
		--[46] = "BSミッション46",
		--[47] = "BSミッション47",
		--[48] = "BSミッション48",
		--[49] = "BSミッション49",
		--[50] = "BSミッション50",
		--[51] = "BSミッション51",
		--[52] = "BSミッション52",
		--[53] = "BSミッション53",
		--[54] = "BSミッション54",
		--[55] = "BSミッション55",
		--[56] = "BSミッション56",
		--[57] = "BSミッション57",
		--[58] = "BSミッション58",
		--[59] = "BSミッション59",
		--[60] = "BSミッション60",
		--[61] = "BSミッション61",
		--[62] = "BSミッション62",
		--[63] = "BSミッション63",
	},
	windurstmissions = {
		[0] = "The Horutoto Ruins Experiment",
		[1] = "The Heart of the Matter",
		[2] = "The Price of Peace",
		[3] = "Lost for Words",
		[4] = "A Testing Time",
		[5] = "The Three Kingdoms",
		--[6] = "The Three Kingdoms (San d'Oria)",
		--[7] = "The Three Kingdoms (Bastok)",
		--[8] = "The Three Kingdoms (San d'Oria)",
		--[9] = "The Three Kingdoms (Bastok)",
		[10] = "To Each His Own Right",
		[11] = "Written in the Stars",
		[12] = "A New Journey",
		[13] = "Magicite",
		[14] = "The Final Seal",
		[15] = "The Shadow Awaits",
		[16] = "Full Moon Fountain",
		[17] = "Saintly Invitation",
		[18] = "The Sixth Ministry",
		[19] = "Awakening of the Gods",
		[20] = "Vain",
		[21] = "The Jester Who'd Be King",
		[22] = "Doll of the Dead",
		[23] = "Moon Reading",
		--[24] = "WSミッション24",
		--[25] = "WSミッション25",
		--[26] = "WSミッション26",
		--[27] = "WSミッション27",
		--[28] = "WSミッション28",
		--[29] = "WSミッション29",
		--[30] = "WSミッション30",
		--[31] = "WSミッション31",
		--[32] = "WSミッション32",
		--[33] = "WSミッション33",
		--[34] = "WSミッション34",
		--[35] = "WSミッション35",
		--[36] = "WSミッション36",
		--[37] = "WSミッション37",
		--[38] = "WSミッション38",
		--[39] = "WSミッション39",
		--[40] = "WSミッション40",
		--[41] = "WSミッション41",
		--[42] = "WSミッション42",
		--[43] = "WSミッション43",
		--[44] = "WSミッション44",
		--[45] = "WSミッション45",
		--[46] = "WSミッション46",
		--[47] = "WSミッション47",
		--[48] = "WSミッション48",
		--[49] = "WSミッション49",
		--[50] = "WSミッション50",
		--[51] = "WSミッション51",
		--[52] = "WSミッション52",
		--[53] = "WSミッション53",
		--[54] = "WSミッション54",
		--[55] = "WSミッション55",
		--[56] = "WSミッション56",
		--[57] = "WSミッション57",
		--[58] = "WSミッション58",
		--[59] = "WSミッション59",
		--[60] = "WSミッション60",
		--[61] = "WSミッション61",
		--[62] = "WSミッション62",
		--[63] = "WSミッション63",
	},
	zilartmissions = {
		[0] = "The New Frontier",
		--[1] = "ZLシナリオ1",
		--[2] = "The Outlands", -- unimplemented
		--[3] = "ZLシナリオ3",
		[4] = "Welcome t'Norg",
		--[5] = "ZLシナリオ5",
		[6] = "Kazham's Chieftainess",
		--[7] = "ZLシナリオ7",
		[8] = "The Temple of Uggalepih",
		--[9] = "ZLシナリオ9",
		[10] = "Headstone Pilgrimage",
		--[11] = "ZLシナリオ11",
		[12] = "Through the Quicksand Caves",
		--[13] = "ZLシナリオ13",
		[14] = "The Chamber of Oracles",
		--[15] = "ZLシナリオ15",
		[16] = "Return to Delkfutt's Tower",
		--[17] = "ZLシナリオ17",
		[18] = "Ro'Maeve",
		--[19] = "ZLシナリオ19",
		[20] = "The Temple of Desolation",
		--[21] = "ZLシナリオ21",
		[22] = "The Hall of the Gods",
		[23] = "The Mithra and the Crystal",
		[24] = "The Gate of the Gods",
		--[25] = "ZLシナリオ25",
		[26] = "Ark Angels",
		[27] = "The Sealed Shrine",
		[28] = "The Celestial Nexus",
		--[29] = "ZLシナリオ29",
		[30] = "Awakening",
		--[31] = "The Last Verse", -- uncompletable
		--[32] = "ZLシナリオ32",
		--[33] = "ZLシナリオ33",
		--[34] = "ZLシナリオ34",
		--[35] = "ZLシナリオ35",
		--[36] = "ZLシナリオ36",
		--[37] = "ZLシナリオ37",
		--[38] = "ZLシナリオ38",
		--[39] = "ZLシナリオ39",
		--[40] = "ZLシナリオ40",
		--[41] = "ZLシナリオ41",
		--[42] = "ZLシナリオ42",
		--[43] = "ZLシナリオ43",
		--[44] = "ZLシナリオ44",
		--[45] = "ZLシナリオ45",
		--[46] = "ZLシナリオ46",
		--[47] = "ZLシナリオ47",
		--[48] = "ZLシナリオ48",
		--[49] = "ZLシナリオ49",
		--[50] = "ZLシナリオ50",
		--[51] = "ZLシナリオ51",
		--[52] = "ZLシナリオ52",
		--[53] = "ZLシナリオ53",
		--[54] = "ZLシナリオ54",
		--[55] = "ZLシナリオ55",
		--[56] = "ZLシナリオ56",
		--[57] = "ZLシナリオ57",
		--[58] = "ZLシナリオ58",
		--[59] = "ZLシナリオ59",
		--[60] = "ZLシナリオ60",
		--[61] = "ZLシナリオ61",
		--[62] = "ZLシナリオ62",
		--[1000] = "To Commence RotZ",
	},
	ahturhganmissions = {
		[0] = "Land of Sacred Serpents",
		[1] = "Immortal Sentries",
		[2] = "President Salaheem",
		[3] = "Knight of Gold",
		[4] = "Confessions of Royalty",
		[5] = "Easterly Winds",
		[6] = "Westerly Winds",
		[7] = "A Mercenary Life",
		[8] = "Undersea Scouting",
		[9] = "Astral Waves",
		[10] = "Imperial Schemes",
		[11] = "Royal Puppeteer",
		[12] = "Lost Kingdom",
		[13] = "The Dolphin Crest",
		[14] = "The Black Coffin",
		[15] = "Ghosts of the Past",
		[16] = "Guests of the Empire",
		[17] = "Passing Glory",
		[18] = "Sweets for the Soul",
		[19] = "Teahouse Tumult",
		[20] = "Finders Keepers",
		[21] = "Shield of Diplomacy",
		[22] = "Social Graces",
		[23] = "Foiled Ambition",
		[24] = "Playing the Part",
		[25] = "Seal of the Serpent",
		[26] = "Misplaced Nobility",
		[27] = "Bastion of Knowledge",
		[28] = "Puppet in Peril",
		[29] = "Prevalence of Pirates",
		[30] = "Shades of Vengeance",
		[31] = "In the Blood",
		[32] = "Sentinels' Honor",
		[33] = "Testing the Waters",
		[34] = "Legacy of the Lost",
		[35] = "Gaze of the Saboteur",
		[36] = "Path of Blood",
		[37] = "Stirrings of War",
		[38] = "Allied Rumblings",
		[39] = "Unraveling Reason",
		[40] = "Light of Judgment",
		[41] = "Path of Darkness",
		[42] = "Fangs of the Lion",
		[43] = "Nashmeira's Plea",
		[44] = "Ragnarok",
		[45] = "Imperial Coronation",
		[46] = "The Empress Crowned",
		--[47] = "Eternal Mercenary",
		--[48] = "ATシナリオ48",
		--[49] = "ATシナリオ49",
		--[50] = "ATシナリオ50",
		--[51] = "ATシナリオ51",
		--[52] = "ATシナリオ52",
		--[53] = "ATシナリオ53",
		--[54] = "ATシナリオ54",
		--[55] = "ATシナリオ55",
		--[56] = "ATシナリオ56",
		--[57] = "ATシナリオ57",
		--[58] = "ATシナリオ58",
		--[59] = "ATシナリオ59",
		--[60] = "ATシナリオ60",
		--[61] = "ATシナリオ61",
		--[62] = "ATシナリオ62",
		--[63] = "ATシナリオ63",
	},
	wotgmissions = {
		[0] = "Cavernous Maws",
		[1] = "Back to the Beginning",
		[2] = "Cait Sith",
		[3] = "The Queen of the Dance",
		[4] = "While the Cat Is Away",
		[5] = "A Timeswept Butterfly",
		[6] = "Purple, The New Black",
		[7] = "In the Name of the Father",
		[8] = "Dancers in Distress",
		[9] = "Daughter of a Knight",
		[10] = "A Spoonful of Sugar",
		[11] = "Affairs of State",
		[12] = "Borne by the Wind",
		[13] = "A Nation on the Brink",
		[14] = "Crossroads of Time",
		[15] = "Sandswept Memories",
		[16] = "Northland Exposure",
		[17] = "Traitor in the Midst",
		[18] = "Betrayal at Beaucedine",
		[19] = "On Thin Ice",
		[20] = "Proof of Valor",
		[21] = "A Sanguinary Prelude",
		[22] = "Dungeons and Dancers",
		[23] = "Distorter of Time",
		[24] = "The Will of the World",
		[25] = "Fate in Haze",
		[26] = "The Scent of Battle",
		[27] = "Another World",
		[28] = "A Hawk in Repose",
		[29] = "The Battle of Xarcabard",
		[30] = "Prelude to a Storm",
		[31] = "Storm's Crescendo",
		[32] = "Into the Beast's Maw",
		[33] = "The Hunter Ensnared",
		[34] = "Flight of the Lion",
		[35] = "Fall of the Hawk",
		[36] = "Darkness Descends",
		[37] = "Adieu, Lilisette",
		[38] = "By the Fading Light",
		[39] = "Edge of Existence",
		[40] = "Her Memories",
		[41] = "Forget Me Not",
		[42] = "Pillar of Hope",
		[43] = "Glimmer of Life",
		[44] = "Time Slips Away",
		[45] = "When Wills Collide",
		[46] = "Whispers of Dawn",
		[47] = "A Dreamy Interlude",
		[48] = "Cait in the Woods",
		[49] = "Fork in the Road",
		[50] = "Maiden of the Dusk",
		[51] = "Where It All Began",
		[52] = "A Token of Troth",
		--[53] = "Lest We Forget",
	},
		-- These misions are listed differently in packets, only current mission id is mentioned.
	copmissions = {
		[1] = {id=101, name="Ancient Flames Beckon"},
		[2] = {id=110, name="__The Rites of Life"},
		[3] = {id=118, name="__Below the Arks"},
		[4] = {id=128, name="__The Mothercrystals"},
		[5] = {id=137, name="The Isle of Forgotten Saints"},
		[6] = {id=138, name="__An Invitation West"},
		[7] = {id=218, name="__The Lost City"},
		[8] = {id=228, name="__Distant Beliefs"},
		[9] = {id=238, name="__An Eternal Melody"},
		[10] = {id=248, name="__Ancient Vows"},
		[11] = {id=257, name="A Transient Dream"},
		[12] = {id=258, name="__The Call of the Wyrmking"},
		[13] = {id=318, name="__A Vessel Without a Captain"},
		[14] = {id=325, name="__The Road Forks"},
		[15] = {id=330, name="____Emerald Waters"},
		[16] = {id=331, name="______Vicissitudes"},
		[17] = {id=335, name="______Descendants of a Line Lost"},
		[18] = {id=339, name="______Louverance"},
		[19] = {id=340, name="____Memories of a Maiden"},
		[20] = {id=341, name="______Comedy of Errors, Act I"},
		[21] = {id=345, name="______Comedy of Errors, Act II"},
		[22] = {id=349, name="______Exit Stage Left"},
		[23] = {id=350, name="__Tending Aged Wounds"},
		[24] = {id=358, name="__Darkness Named"},
		[25] = {id=367, name="The Cradles of Children Lost"},
		[26] = {id=368, name="__Sheltering Doubt"},
		[27] = {id=418, name="__The Savage"},
		[28] = {id=428, name="__The Secrets of Worship"},
		[29] = {id=438, name="__Slanderous Utterings"},
		[30] = {id=447, name="The Return Home"},
		[31] = {id=448, name="__The Enduring Tumult of War"},
		[32] = {id=518, name="__Desires of Emptiness"},
		[33] = {id=530, name="__Three Paths"},
		[34] = {id=540, name="____Past Sins"},
		[35] = {id=542, name="______Southern Legend"},
		[36] = {id=543, name="______Partners Without Fame"},
		[37] = {id=546, name="______A Century of Hardship"},
		[38] = {id=549, name="______Departures"},
		[39] = {id=550, name="____The Pursuit of Paradise"},
		[40] = {id=552, name="______Spiral"},
		[41] = {id=553, name="______Branded"},
		[42] = {id=556, name="______Pride and Honor"},
		[43] = {id=559, name="______And the Compass Guides"},
		[44] = {id=560, name="____Where Messengers Gather"},
		[45] = {id=562, name="______Entanglement"},
		[46] = {id=564, name="______Head Wind"},
		[47] = {id=568, name="______Flames for the Dead"},
		[48] = {id=577, name="Echoes of Time"},
		[49] = {id=578, name="__For Whom the Verse Is Sung"},
		[50] = {id=618, name="__A Place to Return"},
		[51] = {id=628, name="__More Questions Than Answers"},
		[52] = {id=638, name="__One to Be Feared"},
		[53] = {id=647, name="In the Light of the Crystal"},
		[54] = {id=648, name="__Chains and Bonds"},
		[55] = {id=718, name="__Flames in the Darkness"},
		[56] = {id=728, name="__Fire in the Eyes of Men"},
		[57] = {id=738, name="__Calm Before the Storm"},
		[58] = {id=748, name="__The Warrior's Path"},
		[59] = {id=758, name="Emptiness Bleeds"},
		[60] = {id=800, name="__Garden of Antiquity"},
		[61] = {id=818, name="__A Fate Decided"},
		[62] = {id=828, name="__When Angels Fall"},
		[63] = {id=840, name="__Dawn"},
		--[64] = {id=850, name="__The Last Verse"},
		--[65] = {id=1000, name="To Begin CoP..."},
	},
	acpmissions = {
		[1] = {id=0, name="A Crystalline Prophecy"},
		[2] = {id=1, name="The Echo Awakens"},
		[3] = {id=2, name="Gatherer of Light (I)"},
		[4] = {id=3, name="Gatherer of Light (II)"},
		[5] = {id=4, name="Those Who Lurk in Shadows (I)"},
		[6] = {id=5, name="Those Who Lurk in Shadows (II)"},
		[7] = {id=6, name="Those Who Lurk in Shadows (III)"},
		[8] = {id=7, name="Remember Me in Your Dreams"},
		[9] = {id=8, name="Born of Her Nightmares"},
		[10] = {id=9, name="Banishing the Echo"},
		[11] = {id=10, name="Ode of Life Bestowing"},
		--[12] = {id=11, name="A Crystalline Prophecy (Fin.)"},
		--[13] = {id=1000, name="To commence ACP"},
	},
	mkdmissions = {
		[1] = {id=0, name="A Moogle Kupo d'Etat"},
		[2] = {id=1, name="Drenched! It Began with a Raindrop"},
		[3] = {id=2, name="Hasten! In a Jam in Jeuno?"},
		[4] = {id=3, name="Welcome! To My Decrepit Domicile"},
		[5] = {id=4, name="Curses! A Horrifically Harrowing Hex"},
		[6] = {id=5, name="An Errand! The Professor's Price"},
		[7] = {id=6, name="Shock! Arrant Abuse of Authority"},
		[8] = {id=7, name="Lender Beware! Read the Fine Print"},
		[9] = {id=8, name="Rescue! A Moogle's Labor of Love"},
		[10] = {id=9, name="Roar! A Cat Burglar Bares Her Fangs"},
		[11] = {id=10, name="Relief! A Triumphant Return"},
		[12] = {id=11, name="Joy! Summoned to a Fabulous Fete"},
		[13] = {id=12, name="A Challenge! You Could Be a Winner"},
		[14] = {id=13, name="Smash! A Malevolent Menace"},
		--[15] = {id=14, name="A Moogle Kupo d'Etat (Fin.)"},
	},
	asamissions = {
		[1] = {id=0, name="A Shantotto Ascension"},
		[2] = {id=1, name="Burgeoning Dread"},
		[3] = {id=2, name="That Which Curdles Blood"},
		[4] = {id=3, name="Sugar-coated Directive"},
		[5] = {id=4, name="Enemy of the Empire (I)"},
		[6] = {id=5, name="Enemy of the Empire (II)"},
		[7] = {id=6, name="Sugar-coated Subterfuge"},
		[8] = {id=7, name="Shantotto in Chains"},
		[9] = {id=8, name="Fountain of Trouble"},
		[10] = {id=9, name="Battaru Royale"},
		[11] = {id=10, name="Romancing the Clone"},
		[12] = {id=11, name="Sisters in Arms"},
		[13] = {id=12, name="Project: Shantottofication"},
		[14] = {id=13, name="An Uneasy Peace"},
		--[15] = {id=14, name="A Shantotto Ascension (Fin)"},
		--[16] = {id=1000, name="To Begin ASA..."},
	},
	soamissions = {
		[1] = {id=110, name="The Sacred City of Adoulin"},
		[2] = {id=110, name="__Rumors from the West"},
		[3] = {id=112, name="__The Geomagnetron"},
		[4] = {id=116, name="__Onward to Adoulin"},
		[5] = {id=120, name="__Heartwings and the Kindhearted"},
		[6] = {id=122, name="__Pioneer Registration"},
		[7] = {id=124, name="__Life on the Frontier"},
		[8] = {id=126, name="__Meeting of the Minds"},
		[9] = {id=128, name="__Arciela Appears Again"},
		[10] = {id=132, name="The Ancient Pact"},
		[11] = {id=132, name="__Budding Prospects"},
		[12] = {id=134, name="____The Light Shining in Your Eyes"},
		[13] = {id=136, name="____The Heirloom"},
		[14] = {id=138, name="__An Aimless Journey"},
		[15] = {id=140, name="____Ortharsyne"},
		[16] = {id=142, name="____In the Presence of Royalty"},
		[17] = {id=144, name="__The Twin World Trees"},
		[18] = {id=146, name="__Honor and Audacity"},
		[19] = {id=148, name="____The Watergarden Coliseum"},
		[20] = {id=150, name="__Friction and Fissures"},
		[21] = {id=152, name="____The Celennia Memorial Library"},
		[22] = {id=156, name="____For Whom Do We Toil?"},
		[23] = {id=162, name="__Aiming for Ygnas"},
		[24] = {id=164, name="____Calamity in the Kitchen"},
		[25] = {id=168, name="____Arciela's Promise"},
		[26] = {id=170, name="__Predators and Prey"},
		[27] = {id=172, name="____Behind the Sluices"},
		[28] = {id=178, name="____The Leafkin Monarch"},
		[29] = {id=180, name="____Yggdrasil"},
		[30] = {id=184, name="Shadows Upon Adoulin"},
		[31] = {id=184, name="__Return of the Exorcist"},
		[32] = {id=186, name="____The Merciless One"},
		[33] = {id=188, name="____A Curse from the Past"},
		[34] = {id=190, name="____The Purgation"},
		[35] = {id=192, name="____The Key"},
		[36] = {id=194, name="__The Princess's Dilemma"},
		[37] = {id=196, name="____Dark Clouds Ahead"},
		[38] = {id=198, name="____The Smallest of Favors"},
		[39] = {id=200, name="__Summoned by Spirits"},
		[40] = {id=202, name="____Evil Entities"},
		[41] = {id=204, name="____Adoulin Calling"},
		[42] = {id=206, name="____The Disappearance of Nyline"},
		[43] = {id=208, name="____Shared Consciousness"},
		[44] = {id=210, name="____Clear Skies"},
		[45] = {id=212, name="__The Man in Black"},
		[46] = {id=214, name="____To the Victor..."},
		[47] = {id=216, name="____An Extraordinary Gentleman"},
		[48] = {id=220, name="____The Order's Treasures"},
		[49] = {id=222, name="____August's Heirloom"},
		[50] = {id=224, name="__Beauty and the Beast"},
		[51] = {id=226, name="____Wildcat with a Gold Pelt"},
		[52] = {id=228, name="____In Search of Arciela"},
		[53] = {id=232, name="____Looking For Leads"},
		[54] = {id=234, name="__Drifting Northwest"},
		[55] = {id=236, name="____Kumhau, the Flashfrost Naakual"},
		[56] = {id=242, name="____Soul Siphon"},
		[57] = {id=244, name="____Stonewalled"},
		[58] = {id=248, name="____Salvation"},
		[59] = {id=250, name="____Glimmer of Portent"},
		[60] = {id=252, name="The Serpentine Labyrinth"},
		[61] = {id=252, name="__...Into the Fire"},
		[62] = {id=254, name="____Melvien de Malecroix"},
		[63] = {id=256, name="____Courier Catastrophe"},
		[64] = {id=258, name="____Done and Delivered"},
		[65] = {id=260, name="____Ministerial Whispers"},
		[66] = {id=262, name="____A Day in the Life of a Pioneer"},
		[67] = {id=264, name="__Lighting the Way"},
		[68] = {id=266, name="____Sajj'aka"},
		[69] = {id=268, name="____Studying Up"},
		[70] = {id=270, name="____A Vow of Truth"},
		[71] = {id=272, name="____Darrcuiln"},
		[72] = {id=274, name="__The Gates"},
		[73] = {id=278, name="____Morimar"},
		[74] = {id=280, name="____A New Force Arises"},
		[75] = {id=282, name="____The Sacred Sapling"},
		[76] = {id=284, name="____Tree Grafting"},
		[77] = {id=286, name="____A Shrouded Canopy"},
		[78] = {id=288, name="____Leafallia"},
		[79] = {id=290, name="____Rosulatia's Promise"},
		[80] = {id=292, name="____The Lightsland"},
		[81] = {id=294, name="____The Light of Dawn Comes..."},
		[82] = {id=296, name="__Cries from the Deep"},
		[83] = {id=298, name="____Seeds of Doubt"},
		[84] = {id=300, name="____The Tomatoes of Wrath"},
		[85] = {id=302, name="____A Grave Mistake"},
		[86] = {id=306, name="____An Emergency Convocation"},
		[87] = {id=308, name="__Balamor, the Deathborne Xol"},
		[88] = {id=310, name="____Anagnorisis"},
		[89] = {id=312, name="____Just the Thing"},
		[90] = {id=314, name="____Sugarcoated Salvation"},
		[91] = {id=316, name="____Arciela's Resolve"},
		[92] = {id=318, name="__Balamor's Ruse"},
		[93] = {id=320, name="____The Charlatan"},
		[94] = {id=324, name="____Royal Blessings"},
		[95] = {id=326, name="Hades"},
		[96] = {id=326, name="__Arboreal Rumors"},
		[97] = {id=328, name="____Arciela's Missive"},
		[98] = {id=330, name="____Heroes, Unite!"},
		[99] = {id=332, name="____A Portent Most Ominous"},
		[100] = {id=334, name="__Yggdrasil Beckons"},
		[101] = {id=336, name="____Returning to the Trees"},
		[102] = {id=338, name="____The Key to the Turris"},
		[103] = {id=342, name="__Teodor's Summons"},
		[104] = {id=344, name="____The Seventh Guardian"},
		[105] = {id=346, name="____Watery Grave"},
		[106] = {id=350, name="____Blood for Blood"},
		[107] = {id=352, name="__Reckoning"},
		[108] = {id=356, name="____Abomination"},
		[109] = {id=360, name="__Undying Light"},
		[110] = {id=368, name="____The Light Within"},
		--[111] = {id=999, name="__fin"},
		--[112] = {id=1000, name="To begin SoA..."},
	},
	rovmissions = {
		[1] = {id=0, name="Rhapsodies of Vana'diel"},
		[2] = {id=110, name="'Chapter One: Creation and Rebirth'"},
		[3] = {id=110, name="__Resonance"},
		[4] = {id=111, name="__Emissary from the Seas"},
		[5] = {id=112, name="__Set Free"},
		[6] = {id=114, name="__The Beginning"},
		[7] = {id=118, name="__Flames of Prayer"},
		[8] = {id=120, name="__The Path Untraveled"},
		[9] = {id=126, name="__At the Heavens' Door"},
		[10] = {id=128, name="__The Lion's Roar"},
		[11] = {id=130, name="__Eddies of Despair"},
		[12] = {id=134, name="__A Land After Time"},
		[13] = {id=136, name="__Fate's Call"},
		[14] = {id=138, name="__What Lies Beyond"},
		[15] = {id=140, name="__The Ties That Bind"},
		[16] = {id=142, name="__Impurity"},
		[17] = {id=144, name="__The Lost Avatar"},
		[18] = {id=148, name="__Volto Oscuro"},
		[19] = {id=150, name="__Ring My Bell"},
		[20] = {id=152, name="Chapter Two: Revitalization"},
		[21] = {id=152, name="__Spirits Awoken"},
		[22] = {id=154, name="__Crashing Waves"},
		[23] = {id=156, name="__Call to Serve"},
		[24] = {id=158, name="__Numbering Days"},
		[25] = {id=160, name="__Inescapable Binds"},
		[26] = {id=162, name="__Desert Winds"},
		[27] = {id=164, name="__Ever Forward"},
		[28] = {id=168, name="__The Endless Sky"},
		[29] = {id=170, name="__Aphmau's Light"},
		[30] = {id=172, name="__Reunited"},
		[31] = {id=174, name="__Take Wing"},
		[32] = {id=176, name="__Prime Number"},
		[33] = {id=178, name="__From the Ruins"},
		[34] = {id=180, name="__Cauterize"},
		[35] = {id=186, name="__Uncertain Destinations"},
		[36] = {id=188, name="__Ganged Up On"},
		[37] = {id=191, name="__Sacrifice"},
		[38] = {id=194, name="__Somber Dreams"},
		[39] = {id=200, name="__Of Light and Darkness"},
		[40] = {id=202, name="__Temporary Farewells"},
		[41] = {id=204, name="__Brushing Up"},
		[42] = {id=206, name="__Keep On Giving"},
		[43] = {id=208, name="__Past Imperfect"},
		[44] = {id=209, name="__The Cursed Temple"},
		[45] = {id=211, name="__Wisdom of Our Forefathers"},
		[46] = {id=212, name="__Where Divinities Collide"},
		[47] = {id=214, name="__Visions of Dread"},
		[48] = {id=216, name="__To the Skies"},
		[49] = {id=218, name="__Escha - Ru'Aun"},
		[50] = {id=222, name="__The Decisive Heroine"},
		[51] = {id=224, name="__Fall from Grace"},
		[52] = {id=226, name="__Banishing the Darkness"},
		[53] = {id=228, name="__Over the Rainbow"},
		[54] = {id=230, name="__Cacophonous Discord"},
		[55] = {id=232, name="__Eddies of Despair"},
		[56] = {id=234, name="__Pretender to the Throne"},
		[57] = {id=238, name="__Banished"},
		[58] = {id=240, name="__Call of the Void"},
		[59] = {id=244, name="__Both Paths Taken"},
		[60] = {id=250, name="__The Man Behind the Mask"},
		[61] = {id=252, name="__Uncertain Futures"},
		[62] = {id=254, name="Chapter 3: Reckoning"},
		[63] = {id=254, name="__Darkness Beckons"},
		[64] = {id=258, name="__The Brewing Storm"},
		[65] = {id=260, name="__The River Runs Red"},
		[66] = {id=262, name="__The Crucible"},
		[67] = {id=263, name="__Forward Thinking"},
		[68] = {id=264, name="__Tears of the Generals"},
		[69] = {id=266, name="__What He Left Behind"},
		[70] = {id=268, name="__Gone but Not Forgotten"},
		[71] = {id=269, name="__August Artifacts"},
		[72] = {id=270, name="__Solemnity"},
		[73] = {id=272, name="__Eyes on You"},
		[74] = {id=274, name="__Exploring the Ruins"},
		[75] = {id=278, name="__Become Something More"},
		[76] = {id=280, name="__Unshakable Nightmares"},
		[77] = {id=282, name="__What Remains of Hope"},
		[78] = {id=286, name="__Death Cares Not"},
		[79] = {id=288, name="__No Time like the Future"},
		[80] = {id=292, name="__Sin"},
		[81] = {id=296, name="__Penance"},
		[82] = {id=298, name="__Vessel of Light"},
		[83] = {id=300, name="__The Lifestream of Reisenjima"},
		[84] = {id=302, name="__From West to East"},
		[85] = {id=304, name="__Good Things Come in Threes"},
		[86] = {id=306, name="__Tackling the Problem"},
		[87] = {id=308, name="__Way to Divinity"},
		[88] = {id=310, name="__The Winds of Time"},
		[89] = {id=314, name="__Calm After the Storm"},
		[90] = {id=318, name="__Nary a Cloud in Sight"},
		[91] = {id=320, name="__An Unending Song"},
		[92] = {id=324, name="__A Deep Sleep"},
		[93] = {id=326, name="__Guardians"},
		[94] = {id=328, name="__Iroha in Distress"},
		[95] = {id=330, name="__Absolute Trust"},
		[96] = {id=332, name="__The Orb's Radiance"},
		[97] = {id=334, name="__A Rhapsody for the Ages"},
		--[98] = {id=1000, name="To Start RoV..."},
	},
	tvrmissions = {
		[1] = {id=0, name="The Voracious Resurgence"},
		[2] = {id=110, name="__The Gloom Phantom's Approach"},
		[3] = {id=118, name="__The Brygid Cup"},
		[4] = {id=128, name="__The Destiny Destroyers"},
		[5] = {id=138, name="__Kupipi's Dilemma"},
		[6] = {id=146, name="__The Cardians' Duty"},
		[7] = {id=158, name="__Zhuu Buxu's Gambit"},
		[8] = {id=168, name="__Star Onion Fortune"},
		[9] = {id=178, name="__The Doll Whisperer"},
		[10] = {id=192, name="__Dancing Prince"},
		[11] = {id=202, name="__Claidie's Concern"},
		[12] = {id=210, name="__Curilla Unleashed"},
		[13] = {id=228, name="__Run, Excenmille, Run!"},
		[14] = {id=240, name="__Of Knights and Orcs"},
		[15] = {id=256, name="__Best Served Cold"},
		[16] = {id=270, name="__Cornelia's Call to Action"},
		[17] = {id=286, name="__Naja the Ambitious"},
		[18] = {id=298, name="__Raubahn the Blue"},
		[19] = {id=310, name="__Ghatsad's Quandary"},
		[20] = {id=326, name="__The Revelation"},
		[21] = {id=338, name="__Tateeya's Worries"},
		[22] = {id=352, name="__The Seagull Phratrie"},
		[23] = {id=362, name="__The Sea Sage"},
		[24] = {id=380, name="__Sky, Moon, Incantrix"},
		[25] = {id=392, name="__Nii's Last Stand"},
		[26] = {id=414, name="__Dance of the Tengu"},
		[27] = {id=430, name="__Raebrimm's Rebirth"},
		[28] = {id=440, name="__Uran-Mafran of the Maelstrom"},
		[29] = {id=452, name="__Koru-Moru's Hypothesis"},
		[30] = {id=460, name="__Altennia Burns Bright"},
		[31] = {id=468, name="__Maat on the Rampage"},
		[32] = {id=484, name="__Not Just a Pretty Face"},
		[33] = {id=494, name="__Delkfutt the Great"},
		[34] = {id=508, name="__Oshasha Violation"},
		[35] = {id=516, name="__Phantasmic Heroes"},
		[36] = {id=530, name="__Skokkr Undrborn's Temptation"},
		[37] = {id=542, name="__The Prime Weapons"},
		[38] = {id=552, name="__To Movalpolos!"},
		[39] = {id=562, name="__Magh Bihu on the Prowl"},
		[40] = {id=574, name="__101 Dazbogs"},
		[41] = {id=580, name="__Kipdrix the Faithful"},
		[42] = {id=592, name="__Duke Alloces's Decision"},
		[43] = {id=602, name="__Odin's Eye"},
		[44] = {id=612, name="__Moglesse Oblige"},
		[45] = {id=624, name="__The Voracious Beast"},
		--[46] = {id=642, name="__Your Decision"},
		--[47] = {id=999, name="__"},
	}
}