return {
	[0] = "Southern San d'Oria HP#1",
	[1] = "Southern San d'Oria HP#2",
	[2] = "Southern San d'Oria HP#3",
	[3] = "Northern San d'Oria HP#1",
	[4] = "Northern San d'Oria HP#2",
	[5] = "Northern San d'Oria HP#3",
	[6] = "Port San d'Oria HP#1",
	[7] = "Port San d'Oria HP#2",

	[8] = "Port San d'Oria HP#3",
	[9] = "Bastok Mines HP#1",
	[10] = "Bastok Mines HP#2",
	[11] = "Bastok Markets HP#1",
	[12] = "Bastok Markets HP#2",
	[13] = "Bastok Markets HP#3",
	[14] = "Port Bastok HP#1",
	[15] = "Port Bastok HP#2",

	[16] = "Metalworks HP#1",
	[17] = "Windurst Waters HP#1",
	[18] = "Windurst Waters HP#2",
	[19] = "Windurst Walls HP#1",
	[20] = "Windurst Walls HP#2",
	[21] = "Windurst Walls HP#3",
	[22] = "Port Windurst HP#1",
	[23] = "Port Windurst HP#2",

	[24] = "Port Windurst HP#3",
	[25] = "Windurst Woods HP#1",
	[26] = "Windurst Woods HP#2",
	[27] = "Windurst Woods HP#3",
	[28] = "Windurst Woods HP#4",
	[29] = "Ru'Lude Gardens HP#1",
	[30] = "Ru'Lude Gardens HP#2",
	[31] = "Ru'Lude Gardens HP#3",

	[32] = "Upper Jeuno HP#1",
	[33] = "Upper Jeuno HP#2",
	[34] = "Upper Jeuno HP#3",
	[35] = "Lower Jeuno HP#1",
	[36] = "Lower Jeuno HP#2",
	[37] = "Port Jeuno HP#1",
	[38] = "Port Jeuno HP#2",
	[39] = "Kazham HP#1",

	[40] = "Mhaura HP#1",
	[41] = "Norg HP#1",
	[42] = "Rabao HP#1",
	[43] = "Selbina HP#1",
	[44] = "Western Adoulin HP#1",
	[45] = "Eastern Adoulin HP#1",
	[46] = "Ceizak Battlegrounds HP#1",
	[47] = "Foret de Hennetiel HP#1",

	[48] = "Morimar Basalt Fields HP#1",
	[49] = "Yorcia Weald HP#1",
	[50] = "Marjami Ravine HP#1",
	[51] = "Kamihr Drifts HP#1",
	[52] = "Yughott Grotto HP#1",
	[53] = "Palborough Mines HP#1",
	[54] = "Giddeus HP#1",
	[55] = "Fei'Yin HP#1",

	[56] = "Quicksand Caves HP#1",
	[57] = "Den of Rancor HP#1",
	[58] = "Castle Zvahl Keep HP#1",
	[59] = "Ru'Aun Gardens HP#1",
	[60] = "Ru'Aun Gardens HP#2",
	[61] = "Ru'Aun Gardens HP#3",
	[62] = "Ru'Aun Gardens HP#4",
	[63] = "Ru'Aun Gardens HP#5",

	[64] = "Tavnazian Safehold HP#1",
	[65] = "Aht Urhgan Whitegate HP#1",
	[66] = "Nashmau HP#1",
	--[67] = "Unknown HP#1",
	[68] = "Southern San d'Oria [S] HP#1",
	[69] = "Bastok Markets [S] HP#1",
	[70] = "Windurst Waters [S] HP#1",
	[71] = "Upper Delkfutt's Tower HP#1",

	[72] = "The Shrine of Ru'Avitau HP#1",
	[73] = "Riverne - Site #B01 HP#1",
	[74] = "Bhaflau Thickets HP#1",
	[75] = "Caedarva Mire HP#1",
	[76] = "Uleguerand Range HP#1",
	[77] = "Uleguerand Range HP#2",
	[78] = "Uleguerand Range HP#3",
	[79] = "Uleguerand Range HP#4",

	[80] = "Uleguerand Range HP#5",
	[81] = "Attohwa Chasm HP#1",
	[82] = "Pso'Xja HP#1",
	[83] = "Newton Movalpolos HP#1",
	[84] = "Riverne - Site #A01 HP#1",
	[85] = "Al'Taieu HP#1",
	[86] = "Al'Taieu HP#2",
	[87] = "Al'Taieu HP#3",

	[88] = "Grand Palace of Hu'Xzoi HP#1",
	[89] = "The Garden of Ru'Hmet HP#1",
	[90] = "Mount Zhayolm HP#1",
	[91] = "Cape Teriggan HP#1",
	[92] = "The Boyahda Tree HP#1",
	[93] = "Den of Rancor HP#2",
	[94] = "Fei'Yin HP#2",
	[95] = "Ifrit's Cauldron HP#1",

	[96] = "Quicksand Caves HP#2",
	[97] = "Southern San d'Oria HP#4",
	[98] = "Northern San d'Oria HP#4",
	[99] = "Bastok Mines HP#3",
	[100] = "Bastok Markets HP#4",
	[101] = "Port Bastok HP#3",
	[102] = "Metalworks HP#2",
	[103] = "Windurst Waters HP#3",

	[104] = "Norg HP#2",
	[105] = "Rabao HP#2",
	[106] = "Aht Urhgan Whitegate HP#2",
	[107] = "Aht Urhgan Whitegate HP#3",
	[108] = "Aht Urhgan Whitegate HP#4",
	[109] = "Western Adoulin HP#2",
	[110] = "Eastern Adoulin HP#2",
	[111] = "Xarcabard [S] HP#1",

	[112] = "Leafallia HP#1",
	[113] = "Castle Zvahl Keep [S] HP#1",
	[114] = "Qufim Island HP#1",
	[115] = "Toraimarai Canal HP#1",
	[116] = "Ra'Kaznar Inner Court HP#1",
	[117] = "Misareaux Coast HP#1",
	[118] = "Windurst Waters HP#4",
	[119] = "Windurst Woods HP#5",

	[120] = "Tavnazian Safehold HP#2",
	[121] = "Tavnazian Safehold HP#3",
	--[122] = "Unknown HP#2",
	--[123] = "Unknown HP#3",
	--[124] = "Unknown HP#4",
	--[125] = "Unknown HP#5",
	--[126] = "Unknown HP#6",
	--[127] = "Unknown HP#7",
}